<?php
$form=$this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) 
{
    echo "<script type='text/javascript'>".$this->msg."</script>";    
}
if ($this->validacion != null) {
    echo "<script type='text/javascript'>showMessageWarning('Validación','".$this->validacion."');</script>";  
}
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box box-bordered style-primary">
            <div class="box-head">
                <header>
                    <h4 class="text-light">
                       Formulario <strong>Promociones</strong> 
                    </h4>
                </header>
                
                <div class="tools">
                    <div class="btn-group btn-group-transparent">
                        <a class="btn btn-equal btn-sm " data-target="#textModal" data-toggle="modal" onclick="usar_ajax('<?php echo $this->basePath()?>/admin/promocion/buscar','#modal-dialog-display','')"><i class="fa  fa-search"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="box">
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formInput($form->get('idPromocion'));?>
                <?php echo $this->formInput($form->get('idSaldoInventario'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Producto </label>
                        </div>
                        <div class="col-lg-4 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('nombreProducto'));?> 
                        </div>
                        <div class="col-lg-1">
                             <?php echo $this->formElement($form->get('btnBuscarSaldoInventario'));?> 
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Valor Anterior</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('valorAnterior'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Valor Promoción</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('valorPromocion'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Fecha Desde</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('fechaDesde'));?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Fecha Hasta</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('fechaHasta'));?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Estado</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formElement($form->get('estado'));?>
                        </div>
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <?php   
                            echo $this->formElement($form->get('btnGuardar'));
                            echo $this->formElement($form->get('btnModificar'));
                            echo $this->formElement($form->get('btnEliminar'));
                            echo $this->formElement($form->get('btnCancelar'));
                        ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
    </div>
</div>
 