<?php
$form=$this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->basePath().'/admin/categoria/index',
    'method' => 'post',
    'class'=>'form-horizontal',
    'role'=>'form'
));
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) 
{
    echo "<script type='text/javascript'>".$this->msg."</script>";    
}
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-head">
                <header><h4 class="text-light">Formulario <strong>Categoria</strong></h4></header>
            </div>
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formInput($form->get('idCategoria'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Código</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                             <?php echo $this->formInput($form->get('codigo'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Descripción</label>
                        </div>
                        <div class="col-lg-5 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('descripcion'));?>                            
                        </div>
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <?php   echo $this->formElement($form->get('btnGuardar'));
                                echo "<button type='button' class='btn btn-default' onClick=\"limpiarformulario('#frmtipousuario');\">Reset</button>";
                        ?>
                        
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
        <?php if (count($this->categorias)>0) { ?>       
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Categorias</strong> <small>Todas</small></h4></header>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscar" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Código</th>
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Descripción</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->categorias as $categ) {
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$(location).attr('href', '".$this->basePath()."/admin/categoria/index?id=".$categ['idCategoria']."')\">
                                                    <td>".$categ['codigo']."</td>
                                                    <td>".$categ['descripcion']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
 