<script type="text/javascript">
    $(document).ready(function() {
        $('#dtbuscarMunicipio').DataTable();
    });
</script>
<div class="row">
    <div class="col-lg-12">      
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Municipios</strong></h4></header>
                        <a class="btn btn-equal btn-sm btn-close" id="btnCloseBusquedaMunicipio" style="float: right" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></a>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscarMunicipio" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Código</th>
                                            <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Descripción</th>
                                            <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Departamento</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->registros as $obj) {
                                            
                                             $onClick = "$('#idMunicipio').val(" . $obj['idMunicipio'] . ");$('#btnCloseBusquedaMunicipio').click();";
                                                       
                                            if ($this->origen != null) {
                                                $onClick = "$(location).attr('href','" . $this->BasePath() . "/admin/" . $this->origen . "?idMunicipio=" . $obj['idMunicipio'] . "');";
                                            }
                                            
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"". $onClick ."\">
                                                    <td>".$obj['codigo']."</td>
                                                    <td>".$obj['descripcion']."</td>
                                                    <td>".$obj['descripcionDepartamento']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 