<script type="text/javascript">
    function ajustarCantidadProducto(token,idSaldoInventario,cantidad,basePath)
    {
        $("#txtQty"+token).val(parseInt($("#txtQty"+token).val()) + cantidad);
        if (parseInt($("#txtQty"+token).val()) == 0) {
            $("#"+token).remove();
             $(location).attr('href',basePath+"/cart");
        }
        agregarProductoCart(idSaldoInventario,cantidad, basePath);
    }
</script>
<div class="row">
    <div class="col-md-12">
        <header class="content-title">
            <h1 class="title">Shopping Cart</h1>
        </header>
        <div class="xs-margin"></div>
        <!-- space -->
        <div class="row">
            <div class="col-md-12 table-responsive">
                <table class="table cart-table">
                    <thead>
                        <tr>
                            <th class="table-title">Producto</th>
                            <th class="table-title">Referencia</th>
                            <th class="table-title">Precio Unitario</th>
                            <th class="table-title">Cantidad</th>
                            <th class="table-title">SubTotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                        foreach ($this->cart as $token => $producto) 
                        {
                            echo "<tr id='".$token."'>
                                    <td class='item-name-col'>
                                        <figure>
                                            <a href='".str_replace("/public", "", $this->basePath())."/producto/".$producto->getId()."'><img src='".$producto->getImgUrl()."' alt='".$producto->getProduct()."'></a>
                                        </figure>
                                        <header class='item-name'><a href='#'>".$producto->getProduct()."</a></header>
                                        <ul>
                                            <li>Código:".$producto->getCodigo()." - ".$producto->getId()."</li>
                                        </ul>
                                    </td>
                                    <td class='item-code'>".$producto->getReferencia()."</td>
                                    <td class='item-price-col'><span class='item-price-special'>$".number_format($producto->getPrice())."</span></td>
                                    <td>
                                        <div class='custom-quantity-input'>
                                            <input type='text' name='txtQty' id='txtQty".$token."' value='".$producto->getQty()."'>
                                            <a style='cursor:pointer' onclick=\"ajustarCantidadProducto('".$token."',".$producto->getId().", 1, '".$this->basePath()."')\" class='quantity-btn quantity-input-up'>
                                                <i class='fa fa-angle-up'></i>
                                            </a>
                                            <a style='cursor:pointer' onclick=\"ajustarCantidadProducto('".$token."',".$producto->getId().", -1, '".$this->basePath()."')\" class='quantity-btn quantity-input-down'>
                                                <i class='fa fa-angle-down'></i>
                                            </a>
                                        </div>
                                    </td>
                                    <td class='item-total-col'><span class='item-price-special'>$".number_format($producto->getQty()*$producto->getPrice())."</span>
                                        <a style='cursor:pointer' onclick=\"eliminarProductoCart('".$token."','".$this->basePath()."')\" class='close-button'></a>
                                    </td>
                                </tr>";
                        }
                        ?>
                   </tbody>
                </table>
            </div>
            <!-- End .col-md-12 -->
        </div>
        <!-- End .row -->
        <div class="lg-margin"></div>
        <!-- End .space -->
        <div class="row">
           <!-- End .col-md-8 -->
           <div class="col-md-12 col-sm-12 col-xs-12">
              <table class="table total-table">
                 <tbody>
                    <tr>
                       <td class="total-table-title">Subtotal:</td>
                       <td>$<?php echo number_format($this->total_sum)?></td>
                    </tr>
                 </tbody>
                 <tfoot>
                    <tr>
                       <td>Total:</td>
                       <td>$<?php echo number_format($this->total_sum)?></td>
                    </tr>
                 </tfoot>
              </table>
              <div class="md-margin"></div>
              <a href="javascript:$(location).attr('href','<?php echo $this->basePath()?>')" class="btn btn-custom-2">CONTINUAR COMPRANDO</a>
              <a href="#" class="btn btn-custom">CHECKOUT</a>
           </div>
        </div>
        <div class="md-margin2x"></div>
    </div>
</div>