<script type="text/javascript">
    $(document).ready(function() {
        $('#dtbuscarProducto').DataTable();
    });
</script>
<?php 
$form = $this->form;
?>
<div class="row">  
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" id="btnCloseBusquedaProducto" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="textModalLabel"><h4 class="text-light">Búsqueda de <strong>Productos</strong></h4></h4>
        </div>
        <div class="box-body">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-group">
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Marca</label>
                </div>
                <div class="col-lg-3 col-md-11 col-sm-9">
                     <?php echo $this->formElement($form->get('idMarca')->setAttribute('id','idMarcaBusqueda'));?>                            
                </div>
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Categoria </label>
                </div>
                <div class="col-lg-3 col-md-11 col-sm-9">
                     <?php echo $this->formElement($form->get('idCategoria')->setAttribute('id','idCategoriaBusqueda'));?>                            
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Referencia</label>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3">
                    <?php echo $this->formInput($form->get('referencia')->setAttribute('id','referenciaBusqueda'));?>                            
                </div>
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Código</label>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3">
                    <?php echo $this->formInput($form->get('codigo')->setAttribute('id','codigoBusqueda'));?>                            
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Nombre</label>
                </div>
                <div class="col-lg-4 col-md-5 col-sm-6">
                    <?php echo $this->formInput($form->get('nombre')->setAttribute('id','nombreBusqueda'));?>                            
                </div>
            </div>
            <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                <input name="btnBuscar" id="btnBuscar" type="button" title="Buscar" style="margin:2px" class="btn btn-success" value="Buscar" 
                       onclick="usar_ajax('<?php  echo $this->Uri ?>','#'+$.getParameter('modalDialogDisplay','<?php  echo $this->Uri ?>'),'idMarca='+$('#idMarcaBusqueda').val()+'&idCategoria='+$('#idCategoriaBusqueda').val()+'&referencia='+$('#referenciaBusqueda').val()+'&codigo='+$('#codigoBusqueda').val()+'&nombre='+$('#nombreBusqueda').val());">
                <?php
                    echo $this->formElement($form->get('btnCancelar'));
                ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        
        <div class="box "> 
            <div class="box-body table-responsive">
                <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                    <table id="dtbuscarProducto" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                        <thead>
                            <tr role="row">
                                <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Referencia</th>
                                <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Codigo</th>
                                <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Nombre</th>
                                <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Marca</th>
                                <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">Categoria</th>
                            </tr>
                        </thead>
                        <tbody>
                             <?php 
                            foreach ($this->registros as $obj) {
                                
                                $descripcionProducto = $obj['codigo'] .' - '.$obj['nombre'];
                                $onClick = "$('#".$this->campoId."').val(".$obj['idProducto'].");$('#".$this->campoNombre."').val('".$descripcionProducto."');$('#btnCloseBusquedaProducto').click();";
                                
                                if($this->origen != null){
                                    $onClick = "$(location).attr('href','".$this->BasePath()."/admin/".$this->origen."?idProducto=".$obj['idProducto']."&nombreProducto=". $descripcionProducto ."');";
                                }
                                echo "
                                    <tr class='gradeX odd' style='cursor:pointer'onClick=\"".$onClick."\">
                                        <td>".$obj['referencia']."</td>
                                        <td>".$obj['codigo']."</td>
                                        <td>".$obj['nombre']."</td>
                                        <td>".$obj['descripcionMarca']."</td>
                                        <td>".$obj['descripcionCategoria']."</td>
                                    </tr>";
                            }
                            ?>
                        </tbody>
                    </table>
                 </div>
            </div>
        </div>
    </div>
</div>
    

 