<?php
$form=$this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->basePath().'/admin/producto/accesorio',
    'method' => 'post',
    'class'=>'form-horizontal',
    'role'=>'form'
));

?>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-head">
                <header><h4 class="text-light">Formulario <strong>Categoria</strong></h4></header>
            </div>
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formInput($form->get('idCategoria'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Código</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                             <?php echo $this->formInput($form->get('codigo'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Descripción</label>
                        </div>
                        <div class="col-lg-5 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('descripcion'));?>                            
                        </div>
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" class="btn btn-default">Reset</button>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->
</div>
 