<?php
$form=$this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) 
{
    echo "<script type='text/javascript'>".$this->msg."</script>";    
}
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-head">
                <header><h4 class="text-light">Formulario <strong>Producto</strong></h4></header>
            </div>
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formInput($form->get('idProducto'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Marca </label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('idMarca'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Categoria </label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('idCategoria'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Referencia</label>
                        </div>
                        <div class="col-lg-5 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('referencia'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Código</label>
                        </div>
                        <div class="col-lg-5 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('codigo'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Nombre</label>
                        </div>
                        <div class="col-lg-5 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('nombre'));?>                            
                        </div>
                    </div>
                     <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Descripción </label>
                        </div>
                        <div class="col-lg-10 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('descripcion'));?>                            
                        </div>
                    </div>
                     <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Especificación</label>
                        </div>
                        <div class="col-lg-10 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('especificacion'));?>                            
                        </div>
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <?php   
                            echo $this->formElement($form->get('btnGuardar'));
                            echo $this->formElement($form->get('btnModificar'));
                            echo $this->formElement($form->get('btnEliminar'));
                            echo $this->formElement($form->get('btnCancelar'));
                        ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
        <?php if (count($this->registros)>0) { ?>       
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Productos</strong> <small>Todas</small></h4></header>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscar" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Referencia</th>
                                            <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Codigo</th>
                                            <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Nombre</th>
                                            <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Marca</th>
                                            <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">Categoria</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->registros as $obj) {
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$(location).attr('href', '".$this->basePath()."/admin/producto/index?id=".$obj['idProducto']."')\">
                                                    <td>".$obj['referencia']."</td>
                                                    <td>".$obj['codigo']."</td>
                                                    <td>".$obj['nombre']."</td>
                                                    <td>".$obj['descripcionMarca']."</td>
                                                    <td>".$obj['descripcionCategoria']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
 