<div class="row">
   <div class="col-md-12">
      <div class="row">
         <div class="col-md-9 col-sm-8 col-xs-12 main-content">
            <div id="category-header" class="category-banner">
               <img src="<?php echo $this->basePath() ?>/public/images/banner.png" alt="Category banner" class="img-responsive">
               <div class="category-title">
                  <h2>Computers</h2>
                  <p>Aenean dictum libero vitae magna sagittis, eu convallis dolor blandit. Fusce consectur tincidunt pretium aenean tincidunt...</p>
                  <a href="#" class="btn btn-custom">LEARN MORE</a>
               </div>
               <!-- End .category-title -->
            </div>
            <!-- End #category-header -->
            <div class="md-margin"></div>
            <!-- space -->
            <div class="category-toolbar clearfix">
               <div class="toolbox-filter clearfix">
                  <div class="sort-box">
                     <span class="separator">sort by:</span>
                     <div class="btn-group select-dropdown">
                        <button type="button" class="btn select-btn">Position</button>
                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                           <li><a href="#">Date</a></li>
                           <li><a href="#">Name</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="view-box">
                     <a href="category.html" class="active icon-button icon-grid"><i class="fa fa-th-large"></i></a>
                     <a href="category-list.html" class="icon-button icon-list"><i class="fa fa-th-list"></i></a>
                  </div>
                  <!-- End .view-box -->
               </div>
               <!-- End .toolbox-filter -->
               <div class="toolbox-pagination clearfix">
                  <ul class="pagination">
                     <li class="active"><a href="#">1</a></li>
                     <li><a href="#">2</a></li>
                     <li><a href="#">3</a></li>
                     <li><a href="#">4</a></li>
                     <li><a href="#">5</a></li>
                     <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                  </ul>
                  <div class="view-count-box">
                     <span class="separator">view:</span>
                     <div class="btn-group select-dropdown">
                        <button type="button" class="btn select-btn">10</button>
                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                           <li><a href="#">15</a></li>
                           <li><a href="#">30</a></li>
                        </ul>
                     </div>
                  </div>
                  <!-- End .view-count-box -->
               </div>
               <!-- End .toolbox-pagination -->
            </div>
            <!-- End .category-toolbar -->
            <div class="md-margin"></div>
            <!-- .space -->
            <div class="category-item-container">
               <div class="row">
                    <?php
                        foreach ($this->productos as $producto) 
                        {
                            echo "<div class='col-md-4 col-sm-6 col-xs-12'>
                                    <div class='item item-hover'>
                                        <div class'
                                            <figure class='item-image-container'>
                                                <a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>
                                                    <img src='".$producto['urlImg']."' alt='item1' class='item-image'>
                                                    <img src='".$producto['urlImg']."' alt='item1' class='item-image-hover'>
                                                </a>
                                            </figure>
                                            ";
                            if(isset($producto['idPromocion'])){
                                echo "      <div class='item-price-container'>
                                                <span class='old-price'>$".number_format($producto['valorAnterior'])."</span>
                                                <span class='item-price'>$".number_format($producto['valorPromocion'])."</span>
                                            </div>
                                            <span class='discount-rect'>-".number_format($producto['procentajeDescuento'])."%</span>";
                            }
                            else {
                                echo "      <div class='item-price-container'>
                                                <span class='item-price'>$".number_format($producto['valorVenta'])."</span>
                                            </div>";
                            }
                            echo "        
                                          <!--<span class='new-rect'>New</span>-->
                                       </div>

                                       <div class='item-meta-container'>
                                          <div class='ratings-container'>
                                             <div class='ratings'>
                                                <div class='ratings-result' data-result='100'></div>
                                             </div>
                                             <span class='ratings-amount'>
                                             5 Reviews
                                             </span>
                                          </div>
                                          <h3 class='item-name'><a href='product.html'>".$producto['nombre']."</a></h3>
                                          <div class='item-action'>
                                             <a href='#' class='item-add-btn'>
                                             <span class='icon-cart-text'>Add to Cart</span>
                                             </a>
                                          </div>

                                       </div>

                                    </div>

                                 </div>";
                        }
                    ?>
               </div>
               <!-- End .row -->
            </div>
            <!-- End .category-item-container -->
            <div class="pagination-container clearfix">
               <div class="pull-right">
                  <ul class="pagination">
                     <li class="active"><a href="#">1</a></li>
                     <li><a href="#">2</a></li>
                     <li><a href="#">3</a></li>
                     <li><a href="#">4</a></li>
                     <li><a href="#">5</a></li>
                     <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                  </ul>
               </div>
               <!-- End .pull-right -->
               <div class="pull-right view-count-box hidden-xs">
                  <span class="separator">view:</span>
                  <div class="btn-group select-dropdown">
                     <button type="button" class="btn select-btn">10</button>
                     <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                     <i class="fa fa-angle-down"></i>
                     </button>
                     <ul class="dropdown-menu" role="menu">
                        <li><a href="#">15</a></li>
                        <li><a href="#">30</a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <!-- End pagination-container -->
         </div>
         <!-- End .col-md-9 -->
         <aside class="col-md-3 col-sm-4 col-xs-12 sidebar">
            <div class="widget">
               <div class="panel-group custom-accordion sm-accordion" id="category-filter">
                  <div class="panel">
                     <div class="accordion-header">
                        <div class="accordion-title"><span>Categorias</span></div>
                        <!-- End .accordion-title -->
                        <a class="accordion-btn opened"  data-toggle="collapse" data-target="#category-list-1"></a>
                     </div>
                     <!-- End .accordion-header -->
                     <div id="category-list-1" class="collapse in">
                        <div class="panel-body">
                           <ul class="category-filter-list jscrollpane">
                               <?php 
                                    foreach ($this->categorias as $value) {
                                        echo "<li><a href=\"".$this->basePath()."/buscar?idCategoria=".$value['idCategoria']."\">".$value['descripcion']." (".$value['numProducto'].")</a></li>";
                                    }
                                ?>
                           </ul>
                        </div>
                        <!-- End .panel-body -->
                     </div>
                     <!-- #collapse -->
                  </div>
                  <!-- End .panel -->
                  <div class="panel">
                     <div class="accordion-header">
                        <div class="accordion-title"><span>Marcas</span></div>
                        <!-- End .accordion-title -->
                        <a class="accordion-btn opened"  data-toggle="collapse" data-target="#category-list-2"></a>
                     </div>
                     <!-- End .accordion-header -->
                     <div id="category-list-2" class="collapse in">
                        <div class="panel-body">
                           <ul class="category-filter-list jscrollpane">
                                <?php 
                                    foreach ($this->marcas as $value) {
                                        echo "<li><a href=\"".$this->basePath()."/buscar?idMarca=".$value['idMarca']."\">".$value['descripcion']." (".$value['numProducto'].")</a></li>";
                                    }
                                ?>
                           </ul>
                        </div>
                        <!-- End .panel-body -->
                     </div>
                     <!-- #collapse -->
                  </div>
                  <!-- End .panel -->
               </div>
               <!-- .panel-group -->
            </div>
            <!-- End .widget -->
            <div class="widget featured">
               <h3>Featured</h3>
               <div class="featured-slider flexslider sidebarslider">
                  <ul class="featured-list clearfix">
                     <li>
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item5.jpg" alt="item5">
                           </figure>
                           <h5><a href="#">Jacket Suiting Blazer</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="84"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$40</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item1.jpg" alt="item1">
                           </figure>
                           <h5><a href="#">Gap Graphic Cuffed</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="84"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$18</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item2.jpg" alt="item2">
                           </figure>
                           <h5><a href="#">Women's Lauren Dress</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="84"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$30</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                     </li>
                     <li>
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item3.jpg" alt="item3">
                           </figure>
                           <h5><a href="#">Swiss Mobile Phone</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="64"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$39</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item4.jpg" alt="item4">
                           </figure>
                           <h5><a href="#">Zwinzed HeadPhones</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="94"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$18.99</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item7.jpg" alt="item7">
                           </figure>
                           <h5><a href="#">Kless Man Suit</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="74"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$99</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                     </li>
                     <li>
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item4.jpg" alt="item4">
                           </figure>
                           <h5><a href="#">Gap Graphic Cuffed</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="84"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$17</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                        <div class="featured-product clearfix">
                           <figure>
                              <img src="<?php echo $this->basePath() ?>/public/images/products/thumbnails/item6.jpg" alt="item6">
                           </figure>
                           <h5><a href="#">Women's Lauren Dress</a></h5>
                           <div class="ratings-container">
                              <div class="ratings">
                                 <div class="ratings-result" data-result="84"></div>
                              </div>
                              <!-- End .ratings -->
                           </div>
                           <!-- End .rating-container -->
                           <div class="featured-price">$30</div>
                           <!-- End .featured-price -->
                        </div>
                        <!-- End .featured-product -->
                     </li>
                  </ul>
               </div>
               <!-- End .featured-slider -->
            </div>
            <!-- End .widget -->
            <div class="widget banner-slider-container">
               <div class="banner-slider flexslider">
                  <ul class="banner-slider-list clearfix">
                     <li><a href="#"><img src="<?php echo $this->basePath() ?>/public/images/banner1.jpg" alt="Banner 1"></a></li>
                     <li><a href="#"><img src="<?php echo $this->basePath() ?>/public/images/banner2.jpg" alt="Banner 2"></a></li>
                     <li><a href="#"><img src="<?php echo $this->basePath() ?>/public/images/banner3.jpg" alt="Banner 3"></a></li>
                  </ul>
               </div>
            </div>
            <!-- End .widget -->
         </aside>
         <!-- End .col-md-3 -->
      </div>
      <!-- End .row -->
   </div>
   <!-- End .col-md-12 -->
</div>
<!-- End .row -->