<!--link href="<?php echo $this->basePath(); ?>/public/css/animate.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/public/js/wow.js"></script-->
<script type="text/javascript">
    var pageSize =  null;
    $(document).ready(function()
    {
        pageSize = $.getParameter('pageSize',$(location).attr('href'));
        $(".btnPageSize").html(pageSize);
        var filtro = $.getParameter('filtro',$(location).attr('href'));
        if (filtro != null) {
            $('#filtro').val(filtro.toString().replace('+',' ')); 
        }
    });
</script>

<?php 
/*
 *  Script para generar la paginación.
 */
    $pagination = "";
    $class = "active";
    // el numero de la pagina activa
    $pageNumActive = $_GET['pageNumber'] == null ? 1:$_GET['pageNumber'];
    // Se visualiza el boton de anterior si es necesario
    if($pageNumActive > 1){
        $pagination = "<li><a style='cursor:pointer' onclick=\"buscarProductosEnTienda($('#btnPageSize').html(),".($pageNumActive-1).",'".$this->basePath()."')\"><i class='fa fa-angle-left'></i></a></li>";
    }
    for($i=1;$i<=$this->pageCount;$i++) {
        $class ="";
        if ($this->pageNumber == $i)
            $class = "active";
        $pagination .= "<li class='".$class."'><a style='cursor:pointer' onclick=\"buscarProductosEnTienda($('#btnPageSize').html(),".$i.",'".$this->basePath()."')\">$i</a></li>";
    }
    // Se visualiza el boton de siguiente si es necesario
    if ($pageNumActive < $this->pageCount) {
        $pagination .= "<li><a style='cursor:pointer' onclick=\"buscarProductosEnTienda($('#btnPageSize').html(),".($pageNumActive+1).",'".$this->basePath()."')\"><i class='fa fa-angle-right'></i></a></li>";
    }
?>
<div class="row">
   <div class="col-md-12">
      <div class="row">
         <div class="col-md-10 col-sm-9 col-xs-12 main-content">
             
            <!--div id="category-header" class="category-banner">
               <img src="<?php echo $this->basePath() ?>/public/images/banner.png" alt="Category banner" class="img-responsive">
               <div class="category-title">
                  <h2>Computers</h2>
                  <p>Aenean dictum libero vitae magna sagittis, eu convallis dolor blandit. Fusce consectur tincidunt pretium aenean tincidunt...</p>
                  <a href="#" class="btn btn-custom">LEARN MORE</a>
               </div>
               <!-- End .category-title 
            </div>-->
            <!-- End #category-header -->
            <div class="md-margin"></div>
            <!-- space -->
            <div class="category-toolbar clearfix">
              <div class="toolbox-filter clearfix">
									
                <div class="sort-box">
                    <span class="separator">sort by:</span>
                    <div class="btn-group select-dropdown">
                        <button type="button" class="btn select-btn" id="btnSortBy">Más relevantes</button>
                        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Menor Precio</a></li>
                            <li><a href="#">Mayor Precio</a></li>
                        </ul>
                    </div>
                </div>
                </div><!-- End .toolbox-filter -->
                <div class="toolbox-pagination clearfix">
                    <div class="pull-right view-count-box hidden-xs">
                        <span class="separator">view:</span>
                        <div class="btn-group select-dropdown">
                            <button type="button" class="btn select-btn btnPageSize" id="btnPageSize"></button>
                            <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a onclick="buscarProductosEnTienda(10,1,'<?php echo $this->basePath()?>')">10</a></li>
                                <li><a onclick="buscarProductosEnTienda(15,1,'<?php echo $this->basePath()?>')">15</a></li>
                                <li><a onclick="buscarProductosEnTienda(30,1,'<?php echo $this->basePath()?>')">30</a></li>
                           </ul>
                        </div>
                    </div>
                </div><!-- End .toolbox-pagination -->						
            </div>
            <!-- End .category-toolbar -->
            <div class="md-margin"></div>
            <!-- .space -->
            <div class="category-item-container">
               <div class="row">
                    <?php
                        foreach ($this->productos as $producto) 
                        {
                            echo "<div class='col-md-4 col-sm-6 col-xs-12'>
                                    <div class='item item-hover'>
                                        <div 
                                            <figure class='item-image-container'>
                                                <a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>
                                                    <img src='".$producto['urlImg']."' alt='item1' class='item-image'>
                                                    <img src='".$producto['urlImg']."' alt='item1' class='item-image-hover'>
                                                </a>
                                            </figure>
                                            ";
                            if(isset($producto['idPromocion'])){
                                echo "      <div class='item-price-container'>
                                                <span class='old-price'>$".number_format($producto['valorAnterior'])."</span>
                                                <span class='item-price'>$".number_format($producto['valorPromocion'])."</span>
                                            </div>
                                            <span class='discount-rect'>-".number_format($producto['procentajeDescuento'])."%</span>";
                            }
                            else {
                                echo "      <div class='item-price-container'>
                                                <span class='item-price'>$".number_format($producto['valorVenta'])."</span>
                                            </div>";
                            }
                            echo "        
                                          <!--<span class='new-rect'>New</span>-->
                                       </div>

                                       <div class='item-meta-container'>
                                          <div class='ratings-container'>
                                             <div class='ratings'>
                                                <div class='ratings-result' data-result='100'></div>
                                             </div>
                                             <span class='ratings-amount'>
                                             5 Reviews
                                             </span>
                                          </div>
                                          <h3 class='item-name'><a href='product.html'>".$producto['nombre']."</a></h3>
                                          <div class='item-action'>
                                             <a style='cursor:pointer' onclick=\"agregarProductoCart(".$producto['idSaldoInventario'].", 1, '".$this->basePath()."')\" class='item-add-btn'>
                                             <span class='icon-cart-text'>Add to Cart</span>
                                             </a>
                                          </div>
                                       </div>
                                    </div>
                                 </div>";
                        }
                    ?>
               </div>
               <!-- End .row -->
            </div>
            <!-- End .category-item-container -->
            <div class="pagination-container">
                <div class="pull-right">
                    <ul class="pagination">
                        <?php echo $pagination; ?>
                    </ul>
                </div>
            </div>
            <!-- End pagination-container -->
         </div>
         <!-- End .col-md-9 -->
        <div class="row">
            <div class="col-md-2 col-sm-3 col-xs-12">
                <div class="list-group">
                    <a href="#" class="list-group-item active">Categorías</a>
                    <?php 
                        foreach ($this->categorias as $value) {
                            echo " <a href=\"".$this->basePath()."/buscar?pageSize=10&pageNumber=1&idCategoria=".$value['idCategoria']."\" class='list-group-item'>".$value['descripcion']."</a>";
                        }
                    ?>
                </div>

                <div class="list-group">
                    <a href="#" class="list-group-item active">Marcas</a>

                    <?php 
                        foreach ($this->marcas as $value) {
                            echo "<a href=\"".$this->basePath()."/buscar?pageSize=10&pageNumber=1&idMarca=".$value['idMarca']."\" class='list-group-item'>".$value['descripcion']."</a>";
                        }
                    ?>
                </div>

            </div>
        </div>
      </div>
      <!-- End .row -->
   </div>
   <!-- End .col-md-12 -->
</div>
<!-- End .row -->