<?php echo $this->doctype(); 
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public');
}
?>
<html lang="en">
    <head>
        <title>Evo</title>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('keywords', 'your,keywords')
            ->appendName('description', 'Short explanation about this website')
        ?>
        <?php echo $this->headLink(array('rel' => 'stylesheet', 'href' => 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800'))
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/DataTables/TableTools.css?1401297385')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/DataTables/jquery.dataTables.css?1401297385')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/font-awesome.min.css?1400333030')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/boostbox_responsive.css?1400695309')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/boostbox.css?1401297311')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/bootstrap.css?1400695306')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/toastr/toastr.css?1401216363')
                        ->prependStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/select2/select2.css?1401216370')

        ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/script2.js')
            ->prependFile($this->basePath() . '/js/registroobjetos.js')
                
            ->prependFile($this->basePath() . '/admin/assets/js/libs/select2/select2.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/core/demo/DemoUIMessages.js')
            ->prependFile($this->basePath() . '/admin/assets/js/libs/toastr/toastr.min.js')
                
            ->prependFile($this->basePath() . '/admin/assets/js/core/demo/Demo.js')
            ->prependFile($this->basePath() . '/admin/assets/js/core/App.js')
                
            ->prependFile($this->basePath() . '/admin/assets/js/core/demo/DemoTableDynamic.js')
                
            ->prependFile($this->basePath() . '/admin/assets/js/libs/slimscroll/jquery.slimscroll.min.js')
                
            ->prependFile($this->basePath() . '/admin/assets/js/libs/DataTables/extras/TableTools/media/js/TableTools.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/libs/DataTables/extras/ColVis/js/ColVis.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/libs/DataTables/jquery.dataTables.min.js')            
                
            ->prependFile($this->basePath() . '/admin/assets/js/libs/spin.js/spin.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/libs/bootstrap/bootstrap.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/core/BootstrapFixed.js')
            
//            ->prependFile($this->basePath() . '/admin/plugins/flot/jquery.flot.time.min.js')
//            ->prependFile($this->basePath() . '/admin/plugins/flot/jquery.flot.categories.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/libs/jquery/jquery-migrate-1.2.1.min.js')
            ->prependFile($this->basePath() . '/admin/assets/js/libs/jquery/jquery-1.11.0.min.js')
            
            ; ?>
        </head>
    <body class="sidebar-expanded">
        
        <!-- BEGIN HEADER-->
        <header id="header">
            <!-- BEGIN NAVBAR -->
            <nav class="navbar navbar-default" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="btn btn-transparent btn-equal btn-menu" href="javascript:void(0);"><i class="fa fa-bars fa-lg"></i></a>
                    <div class="navbar-brand">
                        <a class="main-brand" href="../../html/dashboards/dashboard.html">
                            <h3 class="text-light text-white"><span>Boost<strong>Box</strong> </span><i class="fa fa-rocket fa-fw"></i></h3>
                        </a>
                    </div><!--end .navbar-brand -->
                    <a class="btn btn-transparent btn-equal navbar-toggle" data-toggle="collapse" data-target="#header-navbar-collapse"><i class="fa fa-wrench fa-lg"></i></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="header-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a target="_blank" href="<?php  echo $this->basePath()?>/client"><i class="fa fa-desktop"></i></a></li>
                    </ul><!--end .nav -->
                    <ul class="nav navbar-nav navbar-right">
                        <li><span class="navbar-devider"></span></li>
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-lg fa-envelope"></i><sup class="badge badge-support2">2</sup></a>
                            <ul class="dropdown-menu animation-zoom">
                                <li class="dropdown-header">Today's messages</li>
                                <li>
                                    <a class="alert alert-warning" href="javascript:void(0);">
                                        <img class="pull-right img-circle dropdown-avatar" src="<?php echo $this->basePath() ?>/admin/assets/img/avatar2.jpg" alt="" />
                                        <strong>Alex Anistor</strong><br/>
                                        <small>Testing functionality...</small>
                                    </a>
                                </li>
                                <li>
                                    <a class="alert alert-info" href="javascript:void(0);">
                                        <img class="pull-right img-circle dropdown-avatar" src="<?php echo $this->basePath() ?>/admin/assets/img/avatar3.jpg" alt="" />
                                        <strong>Alicia Adell</strong><br/>
                                        <small>Reviewing last changes...</small>
                                    </a>
                                </li>
                                <li class="dropdown-header">Options</li>
                                <li><a href="../../html/pages/login.html">View all messages <span class="pull-right"><i class="fa fa-arrow-right"></i></span></a></li>
                                <li><a href="../../html/pages/login.html">Mark as read <span class="pull-right"><i class="fa fa-arrow-right"></i></span></a></li>
                            </ul><!--end .dropdown-menu -->
                        </li><!--end .dropdown -->

                        <li><span class="navbar-devider"></span></li>
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="navbar-profile dropdown-toggle text-bold" data-toggle="dropdown">
                                <?php echo $_SESSION['user']['username'];?>
                                <i class="fa fa-fw fa-angle-down"></i> 
                                <img class="img-circle" src="<?php echo $this->basePath() ?>/admin/assets/img/Ninja Head-48.png" alt="" />
                            </a>
                            <ul class="dropdown-menu animation-slide">
                                <li class="dropdown-header">Config</li>
                                <li><a href="../../html/pages/profile.html">My profile</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo str_replace("/public", "",$this->basePath())?>/admin/login/exit"><i class="fa fa-fw fa-power-off text-danger"></i>Salir</a></li>
                            </ul><!--end .dropdown-menu -->
                        </li><!--end .dropdown -->
                    </ul><!--end .nav -->
                </div><!--end #header-navbar-collapse -->
            </nav>
            <!-- END NAVBAR -->

        </header>
        <!-- END HEADER-->

        <!-- BEGIN BASE-->
        <div id="base">

            <!-- BEGIN SIDEBAR-->
            <div id="sidebar">
                <div class="sidebar-back"></div>
                <div class="sidebar-content">
                    <div class="nav-brand">
                        <a class="main-brand" href="#">
                            <h3 class="text-light text-white"><span><strong>Evo</strong></span><i class="fa fa-mobile-phone"></i></h3>
                        </a>
                    </div>

                    <!-- BEGIN MAIN MENU -->
                    <ul class="main-menu">
                        <!-- Menu Dashboard -->
                        <li>
                            <a href="#" >
                                <i class="fa fa-home fa-fw"></i><span class="title">Dashboard</span>
                            </a>
                        </li><!--end /menu-item -->
                        <!-- Menu UI -->
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa fa-building-o fa-fw"></i><span class="title">Compras</span> <span class="expand-sign">+</span>
                            </a>
                            <ul>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/estadocompra">Estado Compra</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/pedidocompra">Pedido</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa fa-building-o fa-fw"></i><span class="title">División Territorial</span> <span class="expand-sign">+</span>
                            </a>
                            <ul>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/pais">Pais</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/departamento">Departamento</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/municipio">Municipio</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa fa-book fa-fw"></i><span class="title">Inventario</span> <span class="expand-sign">+</span>
                            </a>
                            <!--start submenu -->
                            <ul>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/saldoinventario" >Saldo Inventario</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/movimientoinventario" >Movimiento de Inventarios</a></li>
                            </ul><!--end /submenu -->
                        </li><!--end /menu-item -->
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa fa-desktop fa-fw"></i><span class="title">Producto</span> <span class="expand-sign">+</span>
                            </a>
                            <!--start submenu -->
                            <ul>
                                <li>
                                    <a href="javascript:void(0);"> <span class="expand-sign">+</span>Parámetros</a>
                                    <ul style="display: none;">
                                        <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/categoria" >Categoria</a></li>
                                        <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/marca" >Marca</a></li>
                                    </ul>
                                </li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/producto" >Producto</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/imagenproducto" >Imagenes Producto</a></li>
                                
                            </ul><!--end /submenu -->
                        </li><!--end /menu-item -->
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa  fa-users fa-fw"></i><span class="title">Tercero</span> <span class="expand-sign">+</span>
                            </a>
                            <!--start submenu -->
                            <ul>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/datobasicotercero" >Dato Basico Tercero</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/proveedor" >Proveedor</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/proveedoroficina" >Proveedor Oficina</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/cliente" >Cliente</a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/tipodocumento" >Tipo Documento</a></li>
                            </ul><!--end /submenu -->
                        </li><!--end /menu-item -->
                        <!-- Menu Pages -->
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa fa-unlock-alt fa-fw"></i><span class="title">Seguridad</span> <span class="expand-sign">+</span>
                            </a>
                            <!--start submenu -->
                            <ul>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/usuario" >Usuarios<span class="badge" id="lblNumUsuario">42</span></a></li>
                                <li><a href="<?php echo str_replace("/public","",$this->basePath()) ?>/admin/tipousuario">Tipo Usuarios</a></li>
                            </ul>
                        </li><!--end /menu-item -->

                        <!-- Menu Charts -->
                        <li>
                            <a href="#" >
                                <i class="fa fa-bar-chart-o fa-fw"></i><span class="title">Reporte</span>
                            </a>
                        </li><!--end /menu-item -->
                    </ul><!--end .main-menu -->
                    <!-- END MAIN MENU -->

                </div>
            </div><!--end #sidebar-->
            <!-- END SIDEBAR -->

            <!-- BEGIN CONTENT-->
            <div id="content">
                <section>
<!--                            <ol class="breadcrumb">
                                <li><a href="http://localhost/CodeCovers/www.codecovers.com/boostbox">home</a></li>
                                <li class="active">Form layouts</li>
                        </ol>-->
                        <div class="section-header">
                            <h3 class="text-standard"><i class="fa fa-fw fa-arrow-circle-right text-gray-light"></i> Evo <small></small></h3>
                        </div>
                        <div class="section-body">
                            <!-- START HORIZONTAL FORM -->
                            <div class="row">
                                <div class="col-lg-12">
                                    <?php echo $this->content; ?>
                                </div><!--end .col-lg-12 -->
                            </div><!--end .row -->
                            <!-- END HORIZONTAL FORM -->


                        </div><!--end .section-body -->
                </section>

            </div><!--end #content-->
            <!-- END CONTENT -->

        </div><!--end #base-->
        <div class="modal fade" id="textModal" tabindex="-1" role="dialog" aria-labelledby="textModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-dialog" id="modal-dialog-display">
                
            </div><!-- /.modal-dialog -->
        </div>
    </body>
</html>
