<script type="text/javascript">
    $(document).ready(function() {
        $('#dtbuscarProveedor').DataTable();   
    });
</script>
<div class="row">
    <div class="col-lg-12">  
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Proveedores</strong></h4></header>
                        <a class="btn btn-equal btn-sm btn-close" id="btnClosePop" style="float: right" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></a>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscarProveedor" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Tercero</th>
                                            <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Email</th>
                                            <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Numero Cuenta</th>
                                            <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Tipo Cuenta</th>
                                            <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">Via Pago</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->registros as $obj) {
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$('#idProveedor').val(".$obj['idProveedor'].");$('#btnClosePop').click();$('#modal-dialog-display').html('')\")\">
                                                    <td>".$obj['descripcionTercero']."</td>
                                                    <td>".$obj['email']."</td>
                                                    <td>".$obj['numCuentaBancaria']."</td>
                                                    <td>".$obj['descripcionTipoCuenta']."</td>
                                                    <td>".$obj['descripcionViaPago']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 