<?php
$form = $this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) {
    echo "<script type='text/javascript'>" . $this->msg . "</script>";
}
?>
<script type="text/javascript">
    var numRows = 0;

    function AddRow()
    {
        numRows++;
        var parametrosGet = "?campoId=idSaldoInventario" + numRows + "&campoNombre=nombreProducto" + numRows + "&campoIdProducto=hidIdProducto" + numRows;
        parametrosGet += "&campoValorVenta=hidValorVenta" + numRows + "&campoCantidad=hidCantidad" + numRows;
        var onClick = "onclick=\"usar_ajax('<?php echo $this->basePath() ?>/admin/saldoinventario/buscar" + parametrosGet + "','#modal-dialog-display','')\"";
        var cadena = "<tr id='pedidoVentaPosicion" + numRows + "'>";
        cadena += "<td>" + numRows + "</td>";
        cadena += "<td><div class='col-lg-8 col-md-4 col-sm-4'>";
        cadena += "<input class='form-control' id='idSaldoInventario" + numRows + "' name='idSaldoInventario" + numRows + "' type='hidden'>";
        cadena += "<input class='form-control' id='hidIdProducto" + numRows + "' name='hidIdProducto" + numRows + "' type='hidden'>";
        cadena += "<input class='form-control' id='hidValorVenta" + numRows + "' name='hidValorVenta" + numRows + "' type='hidden'>";
        cadena += "<input class='form-control' id='hidCantidad" + numRows + "' name='hidCantidad" + numRows + "' type='hidden'>";
        cadena += "<input class='form-control' id='nombreProducto" + numRows + "' type='text' required='required' onkeypress='return false'></div>";
        cadena += "<input type='button' " + onClick + " data-target='#textModal' data-toggle='modal' style='margin:2px' class='btn btn-support2' value='Buscar'></td>";
        
        cadena += "<td><input name=\"cantidad" + numRows + "\" id=\"cantidad" + numRows + "\" type='text' required='required' placeholder='Cantidad' maxlength='9' class='form-control' onkeyup=\"totalRow("+ numRows +")\" onkeypress=\"return validarTecla(event,'num')\"></td>";
        cadena += "<td><input name=\"valorVenta" + numRows + "\" id=\"valorVenta" + numRows + "\" type='text' required='required' placeholder='Valor Venta' maxlength='20' readonly class='form-control' onkeypress=\"return validarTecla(event,'num')\"></td>";
        cadena += "<td><a class='btn btn-danger' onclick=\"$('#pedidoVentaPosicion" + numRows + "').remove()\"><i class='fa  fa-minus-square'></i></a></td></tr>";
        $('#tBodyPedido').append(cadena);
    }
    
    function totalRow(numRows){
        
        var cantidad = $("#cantidad" + numRows).val();
        var valorVenta = $("#hidValorVenta" + numRows).val()
        var cantidadActual = $("#hidCantidad" + numRows).val();
        var total = 0;
        if(cantidad != "" && valorVenta != "" && cantidadActual != ""){
            
            cantidad = parseFloat(cantidad);
            valorVenta = parseFloat(valorVenta);
            cantidadActual = parseInt(cantidadActual);
            
            if(cantidad < 0){
               cantidad =0;
            }
            if(cantidad > cantidadActual){
                cantidad = cantidadActual;
                $("#cantidad" + numRows).val(cantidad);
            }
            
            if(cantidad > 0 && valorVenta > 0){
                total = cantidad * valorVenta;
            }
        }
        $("#valorVenta" + numRows).val(total);
        
    }
    $(document).ready(function () {
        AddRow();
        
        // Valida que el formulario no tenga ningun detalle con productos repetidos
        $("#<?php echo $form->getName() ?>").submit(function (event) {
            var productos = []
            $("#<?php echo $form->getName() ?>").find("input[name^='idSaldoInventario']").each(function () {
                if (jQuery.inArray(productos[0], $(this).val()) > -1)
                {
                    showMessageWarning('Productos Repetidos', 'En el detalle del pedido no se puede adicionar mas de una vez un producto')
                    event.preventDefault();
                    return;
                }
                productos.push($(this).val());
            });
        });
    });
</script>

<div class="row">
    <div class="col-lg-12">
        <div class="box box-bordered style-primary">
            <div class="box-head">
                <header>
                    <h4 class="text-light">
                        <i class="fa fa-fw fa-laptop"></i>  <strong>Pedido Venta</strong>
                    </h4>

                </header>
            </div>

        </div>
    </div>
    <div class="col-lg-12">

        <div class="box">

            <div class="box-body">
                <?php echo $this->form()->openTag($form);
                echo $this->formElement($form->get('idCliente'));
                ?>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Número Pedido</label>
                    </div>
                    <div class="col-lg-2 col-md-3 col-sm-4">
                        <?php echo $this->formInput($form->get('numeroPedido')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Cliente</label>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-5">
                        <?php echo $this->formInput($form->get('nombreCliente')); ?>  
                    </div>
                    <?php echo $this->formElement($form->get('btnBuscarCliente')); ?>  
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Documento Pago</label>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-5">
                        <?php echo $this->formElement($form->get('file-documentoPago')); ?>   
                        <p class="help-block">Escanee el documento de pago.</p>
                    </div>

                </div>
                <div class="row">

                    <div class="col-lg-12">
                        <div class="box box-outlined style-primary1">
                            <div class="box-head">
                                <header><h4 class="text-light"><i class="fa fa-fw  fa-list"></i> Pedido <strong>Detalle</strong></h4></header>
                                <div class="tools">
                                    <div class="btn-group btn-group-transparent">
                                        <a class="btn btn-equal btn-sm " onclick="AddRow()" title="Agregar nuevo detalle"><i class="fa fa-plus"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="box-body" style="display: block;">
                                <div class="table-responsive no-margin">
                                    <table class="table table-striped no-margin">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Producto</th>
                                                <th>Cantidad</th>
                                                <th>Valor Venta</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody id="tBodyPedido">
                                            <!--  -->
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div><!--end .col-lg-6 -->
                </div>
                <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                    <?php echo $this->formElement($form->get('btnGuardar')); ?>  
                    <?php echo $this->formElement($form->get('btnCancelar')); ?> 
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->

</div>