<?php
$form=$this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) 
{
    echo "<script type='text/javascript'>".$this->msg."</script>";    
}
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-head">
                <header><h4 class="text-light">Formulario <strong>Saldo Inventario</strong></h4></header>
            </div>
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formInput($form->get('idSaldoInventario'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Producto </label>
                        </div>
                        <div class="col-lg-4 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('idProducto'));?> 
                            
                        </div>
                        <div class="col-lg-1 col-md-2 col-sm-3">
                             <?php echo $this->formElement($form->get('btnBuscarProducto'));?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Proveedor</label>
                        </div>
                        <div class="col-lg-4 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('idProveedor'));?>                            
                        </div>
                        <div class="col-lg-1 col-md-2 col-sm-3">
                             <?php echo $this->formElement($form->get('btnBuscarProveedor'));?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Cantidad</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('cantidad'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Valor Compra</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('valorCompra'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Valor Venta</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('valorVenta'));?>
                        </div>
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <?php   
                            echo $this->formElement($form->get('btnGuardar'));
                            echo $this->formElement($form->get('btnModificar'));
                            echo $this->formElement($form->get('btnEliminar'));
                            echo $this->formElement($form->get('btnCancelar'));
                        ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
        <?php if (count($this->registros)>0) { ?>       
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Saldo Inventarios</strong> <small>Todas</small></h4></header>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscar" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Producto</th>
                                            <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Proveedor</th>
                                            <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Cantidad</th>
                                            <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Valor Compra</th>
                                            <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">valorVenta</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->registros as $obj) {
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$(location).attr('href', '".$this->basePath()."/admin/saldoinventario/index?id=".$obj['idSaldoInventario']."')\">
                                                    <td>".$obj['nombreProducto']."</td>
                                                    <td>".$obj['descripcionProveedor']."</td>
                                                    <td>".$obj['cantidad']."</td>
                                                    <td>".$obj['valorCompra']."</td>
                                                    <td>".$obj['valorVenta']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
 