<script type="text/javascript">
    $(document).ready(function() {
        $('#dtbuscarTercero').DataTable();   
    });
</script>
<div class="row">
    <div class="col-lg-12"> 
            <div class="row">  
                <div class="col-lg-12">
                    <div class="box box-bordered">
                        <div class="box-head">
                            <header><h4 class="text-light"><strong>Dato Basico Terceros</strong></h4></header>
                            <a class="btn btn-equal btn-sm btn-close" id="btnClosePop" style="float: right" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="box"> 
                            <div class="box-body table-responsive">
                                <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                    <table id="dtbuscarTercero" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                        <thead>
                                            <tr role="row">
                                                <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Tipo Documento</th>
                                                <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Nif</th>
                                                <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Descripción</th>
                                                <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Primer Nombre</th>
                                                <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">Segundo Nombre</th>
                                                <th lass="sorting" role="columnheader" tabindex="5" aria-controls="dtcrudindex" rowspan="1" colspan="1">Primer Apellido</th>
                                                <th lass="sorting" role="columnheader" tabindex="6" aria-controls="dtcrudindex" rowspan="1" colspan="1">Segundo Apellido</th>
                                                <th lass="sorting" role="columnheader" tabindex="7" aria-controls="dtcrudindex" rowspan="1" colspan="1">Dirección</th>
                                                <th lass="sorting" role="columnheader" tabindex="8" aria-controls="dtcrudindex" rowspan="1" colspan="1">Teléfono</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            foreach ($this->registros as $obj) {
                                                echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$('#idDatoBasicoTercero').val(".$obj['idDatoBasicoTercero'].");$('#btnClosePop').click();$('#modal-dialog-display').html('')\")\">
                                                    <td>". $obj['descripcionTipoDocumento'] ."</td>
                                                    <td>" . $obj['nit'] . "</td>
                                                    <td>" . $obj['descripcion'] . "</td>
                                                    <td>" . $obj['primerNombre'] . "</td>
                                                    <td>" . $obj['segundoNombre'] . "</td>
                                                    <td>" . $obj['primerApellido'] . "</td>
                                                    <td>" . $obj['segundoApellido'] . "</td>
                                                    <td>" . $obj['direccion'] . "</td>
                                                    <td>" . $obj['telefono'] . "</td>
                                                </tr>";
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
