<?php
$form = $this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) {
    echo "<script type='text/javascript'>" . $this->msg . "</script>";
}
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box box-bordered style-primary">
            <div class="box-head">
                <header>
                    <h4 class="text-light">
                       Formulario <strong>Dato Basico Tercero</strong> 
                    </h4>
                </header>
                
                <div class="tools">
                    <div class="btn-group btn-group-transparent">
                        <a class="btn btn-equal btn-sm " data-target="#textModal" data-toggle="modal" onclick="showBusquedaOnModal(this,'<?php echo $this->basePath()?>/admin/datobasicotercero/buscar?origen=datobasicotercero/index','')"><i class="fa  fa-search"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-lg-12">
        <div class="box">
          
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formInput($form->get('idDatoBasicoTercero')); ?>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Tipo Documento</label>
                    </div>
                    <div class="col-lg-3 col-md-11 col-sm-9">
                        <?php echo $this->formElement($form->get('idTipoDocumento')); ?>                          
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Nit</label>
                    </div>
                    <div class="col-lg-3 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('nit')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Descripción</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('descripcion')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Primer Nombre</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('primerNombre')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Segundo Nombre</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('segundoNombre')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Primer Apellido</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('primerApellido')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Segundo Apellido</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('segundoApellido')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Dirección</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('direccion')); ?>                            
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <label for="email1" class="control-label">Teléfono</label>
                    </div>
                    <div class="col-lg-5 col-md-11 col-sm-9">
                        <?php echo $this->formInput($form->get('telefono')); ?>                            
                    </div>
                </div>


                <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                    <?php
                    echo $this->formElement($form->get('btnGuardar'));
                    echo $this->formElement($form->get('btnModificar'));
                    echo $this->formElement($form->get('btnEliminar'));
                    echo $this->formElement($form->get('btnCancelar'));
                    ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
    </div>
</div>
