<div class="row">
   <div class="col-md-12">
      <header class="content-title">
         <h1 class="title">Ingresar o Crear una cuenta</h1>
         <div class="md-margin"></div>
         <!-- space -->
      </header>
      <div class="row">
         <div class="col-md-6 col-sm-6 col-xs-12">
            <h2>Nuevo Cliente</h2>
            <p>Al crear una cuenta en nuestra tienda, usted será capaz de moverse a través del proceso de compra más rápidamente, almacenar múltiples direcciones de envío, ver y rastrear sus pedidos en su cuenta y más.</p>
            <div class="md-margin"></div>
            <!-- space -->
            <a href="<?php echo $this->basePath()?>/singup" class="btn btn-custom-2">Crear cuenta</a>
            <div class="lg-margin"></div>
            <!-- space -->
         </div>
         <!-- End .col-md-6 -->
         <div class="col-md-6 col-sm-6 col-xs-12">
            <h2>Clientes Registrados</h2>
            <p>Si usted tiene una cuenta con nosotros, por favor conectarse.</p>
            <div class="xs-margin"></div>
            <form id="login-form" method="post" action="<?php echo str_replace("/public", "",  $this->basePath())?>/application/login/login">
               <div class="input-group">
                  <span class="input-group-addon"><span class="input-icon input-icon-email"></span><span class="input-text">Email&#42;</span></span>
                  <input type="text" id="email" name="email" required class="form-control input-lg" placeholder="Email">
               </div>
               <!-- End .input-group -->
               <div class="input-group xs-margin">
                  <span class="input-group-addon"><span class="input-icon input-icon-password"></span><span class="input-text">Password&#42;</span></span>
                  <input type="password" id="pass" name="pass" required class="form-control input-lg" placeholder="Password">
               </div>
               <!-- End .input-group -->
               <span class="help-block text-right"><a href="#">Forgot your password?</a></span>
               <button class="btn btn-custom-2">LOGIN</button>
            </form>
            <div class="sm-margin"></div>
            <!-- space -->
         </div>
         <!-- End .col-md-6 -->
      </div>
      <!-- End.row -->
   </div>
   <!-- End .col-md-12 -->
</div>
<!-- End .row -->