<?php
echo $this->doctype();
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
?>
<!--[if IE 8]> <html class="ie8"> <![endif]-->
<!--[if IE 9]> <html class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title>EvoMaster</title>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('keywords', 'tegnologia,outlet')
                ->appendName('description', 'Tienda online de productos tecnologicos a bajos precios')
        ?>
        <!--[if IE]> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <![endif]-->
        
        <?php
        echo $this->headLink(array('rel' => 'stylesheet', 'href' => 'http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic%7CPT+Gudea:400,700,400italic%7CPT+Oswald:400,700,300','id'=>'googlefont'),'APPEND')
                ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/css/prettyPhoto.css')
                ->appendStylesheet($this->basePath() . '/css/owl.carousel.css')
                ->appendStylesheet($this->basePath() . '/css/style.css')
                ->appendStylesheet($this->basePath() . '/css/responsive.css')
                ->appendStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/toastr/toastr.css?1401216363')
                ->appendStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/select2/select2.css?1401216370')
                //->appendStylesheet($this->basePath() . '/images/icons/icon.png', 'image/png', '', array('rel'=>'icon'))
                //->appendStylesheet($this->basePath() . '/images/icons/apple-icon-57x57.png', 'image/png', '', array('rel'=>'apple-touch-icon','sizes='=>'57x57'))
                //->appendStylesheet($this->basePath() . '/images/icons/apple-icon-72x72.png', 'image/png', '', array('rel'=>'apple-touch-icon','sizes='=>'72x72'))
                
        ?>
               
        <!--- jQuery -->
        <?php
        echo $this->headScript()
                ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js');
        ?>
        <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
        <script>window.jQuery || document.write('<script src="<?php echo $this->basePath()?>/js/jquery-2.22.2.min.js"><\/script>')</script>

		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->
	    
		<style id="custom-style">
		
		</style>
        <!-- END -->
    
    </head>
    <body>
    <div id="wrapper">
    	<header id="header" class="header4">
            <div id="header-top">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="header-top-left">
                                <ul id="top-links" class="clearfix">
                                    <li><a href="#" title="My Wishlist"><span class="top-icon top-icon-pencil"></span><span class="hide-for-xs">My Wishlist</span></a></li>
                                    <li><a href="#" title="My Account"><span class="top-icon top-icon-user"></span><span class="hide-for-xs">My Account</span></a></li>
                                    <li><a href="cart.html" title="My Cart"><span class="top-icon top-icon-cart"></span><span class="hide-for-xs">My Cart</span></a></li>
                                    <li><a href="checkout.html" title="Checkout"><span class="top-icon top-icon-check"></span><span class="hide-for-xs">Checkout</span></a></li>
                                </ul>
                            </div><!-- End .header-top-left -->
                            <div class="header-top-right">
                                <div class="header-text-container pull-right">
                                        <p class="header-link"><a href="#">login</a>&nbsp;or&nbsp;<a href="#">create an account</a></p>
                                </div><!-- End .pull-right -->

                                <div class="dropdown-cart-menu-container pull-right">
                                    <div class="btn-group dropdown-cart">
                                        <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">
                                            <span class="cart-menu-icon"></span>
                                            0 item(s) <span class="drop-price">- $0.00</span>
                                        </button>
                                        <!--
                                        <div class="dropdown-menu dropdown-cart-menu pull-right clearfix" role="menu">
                                            <p class="dropdown-cart-description">Recently added item(s).</p>
                                            <ul class="dropdown-cart-product-list">
                                                <li class="item clearfix">
                                                    <a href="#" title="Delete item" class="delete-item"><i class="fa fa-times"></i></a>
                                                    <a href="#" title="Edit item" class="edit-item"><i class="fa fa-pencil"></i></a>
                                                    <figure>
                                                        <a href="product.html"><img src="<?php echo $this->basePath()?>/images/products/thumbnails/item12.jpg" alt="phone 4"></a>
                                                    </figure>
                                                    <div class="dropdown-cart-details">
                                                        <p class="item-name">
                                                        <a href="product.html">Cam Optia AF Webcam </a>
                                                        </p>
                                                        <p>
                                                            1x
                                                            <span class="item-price">$499</span>
                                                        </p>
                                                    </div><!-- End .dropdown-cart-details ->
                                                </li>
                                                <li class="item clearfix">
                                                    <a href="#" title="Delete item" class="delete-item"><i class="fa fa-times"></i></a>
                                                    <a href="#" title="Edit item" class="edit-item"><i class="fa fa-pencil"></i></a>
                                                    <figure>
                                                        <a href="product.html"><img src="<?php echo $this->basePath()?>/images/products/thumbnails/item13.jpg" alt="phone 2"></a>
                                                    </figure>
                                                    <div class="dropdown-cart-details">
                                                        <p class="item-name">
                                                            <a href="product.html">Iphone Case Cover Original</a>
                                                        </p>
                                                        <p>
                                                            1x
                                                            <span class="item-price">$499<span class="sub-price">.99</span></span>
                                                        </p>
                                                    </div><!-- End .dropdown-cart-details ->
                                                </li>
                                            </ul>

                                            <ul class="dropdown-cart-total">
                                                <li><span class="dropdown-cart-total-title">Shipping:</span>$7</li>
                                                <li><span class="dropdown-cart-total-title">Total:</span>$1005<span class="sub-price">.99</span></li>
                                            </ul><!-- .dropdown-cart-total ->
                                            <div class="dropdown-cart-action">
                                                <p><a href="cart.html" class="btn btn-custom-2 btn-block">Cart</a></p>
                                                <p><a href="checkout.html" class="btn btn-custom btn-block">Checkout</a></p>
                                            </div><!-- End .dropdown-cart-action ->

                                        </div><!-- End .dropdown-cart -->
                                    </div><!-- End .btn-group -->
                                </div><!-- End .dropdown-cart-menu-container -->

                                <div class="header-top-dropdowns pull-right">
                                    <!--<div class="btn-group dropdown-money">
                                        <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">
                                            <span class="hide-for-xs">US Dollar</span><span class="hide-for-lg">$</span>
                                        </button>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            <li><a href="#"><span class="hide-for-xs">Euro</span><span class="hide-for-lg">&euro;</span></a></li>
                                            <li><a href="#"><span class="hide-for-xs">Pound</span><span class="hide-for-lg">&pound;</span></a></li>
                                        </ul>
                                    </div><!-- End .btn-group -->
                                    <div class="btn-group dropdown-language">
                                        <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">
                                            <span class="flag-container"><img src="<?php echo $this->basePath()?>/images/england-flag.png" alt="flag of england"></span>
                                            <span class="hide-for-xs">Español</span>
                                        </button>
                                        
                                    </div><!-- End .btn-group -->
                                </div><!-- End .header-top-dropdowns -->
                            </div><!-- End .header-top-right -->
                        </div><!-- End .col-md-12 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End #header-top -->

            <div id="inner-header">
                <div id="main-nav-container">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 clearfix">
                                <div id="menu-wrapper" class="clearfix">
                                    <div class="logo-container">
                                        <h1 class="logo clearfix">
                                            <span>Responsive eCommerce Template</span>
                                            <a href="index.html" title="Venedor eCommerce Template"><img src="<?php echo $this->basePath()?>/images/logo4.png" alt="Venedor Commerce Template" width="184" height="60"></a>
                                        </h1>
                                    </div><!-- End .logo-container -->
                                    <div id="menu-right-side" class="clerfix">
                                        <div id="quick-access">
                                            <form class="form-inline quick-search-form" role="form" action="#">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" placeholder="Search here">
                                                </div><!-- End .form-inline -->
                                                <button type="submit" id="quick-search" class="btn btn-custom"></button>
                                            </form>
                                        </div><!-- End #quick-access -->
                                        <nav id="main-nav">
                                            <div id="responsive-nav">
                                                <div id="responsive-nav-button">
                                                    Menu <span id="responsive-nav-button-icon"></span>
                                                </div><!-- responsive-nav-button -->
                                            </div>
                                            <ul class="menu clearfix">
                                            <li>
                                                <a class="active" href="index.html">Home</a>
                                                <ul>
                                                    <li><a href="../green/index.html">Home 1</a></li>
                                                </ul>
                                            </li>
                                            <li class="mega-menu-container"><a href="#">SHOP</a>
                                                <div class="mega-menu clearfix">
                                                    <div class="col-5">
                                                        <a href="category.html" class="mega-menu-title">Clothing</a><!-- End .mega-menu-title -->
                                                        <ul class="mega-menu-list clearfix">
                                                            <li><a href="#">Dresses</a></li>
                                                           
                                                        </ul>
                                                    </div><!-- End .col-5 -->
                                                    <div class="col-5">
                                                        <a href="category.html" class="mega-menu-title">Shoes</a><!-- End .mega-menu-title -->
                                                        <ul class="mega-menu-list clearfix">
                                                            <li><a href="#">Formal Shoes</a></li>
                                                            
                                                        </ul>
                                                    </div><!-- End .col-5 -->
                                                    <div class="col-5">
                                                        <a href="category.html" class="mega-menu-title">Accessories</a><!-- End .mega-menu-title -->
                                                        <ul class="mega-menu-list clearfix">
                                                            <li><a href="#">Bags &amp; Purses</a></li>
                                                            
                                                        </ul>
                                                    </div><!-- End .col-5 -->
                                                    <div class="col-5">
                                                        <a href="category.html" class="mega-menu-title">Sports</a><!-- End .mega-menu-title -->
                                                        <ul class="mega-menu-list clearfix">
                                                            <li><a href="#">Sport Tops &amp; Vests</a></li>
                                                            
                                                        </ul>
                                                    </div><!-- End .col-5 -->

                                                    <div class="col-5">
                                                        <a href="category.html" class="mega-menu-title">Maternity</a><!-- End .mega-menu-title -->
                                                        <ul class="mega-menu-list clearfix">
                                                            <li><a href="#">Tops &amp; Skirts</a></li>
                                                            
                                                        </ul>
                                                    </div><!-- End .col-5 -->
                                                </div><!-- End .mega-menu -->
                                            </li>

                                            <li>
                                                <a href="#">PAGES</a>
                                                <ul>
                                                    <li><a href="#">Headers</a>
                                                        <ul>
                                                            <li><a href="header1.html">Header Version 1</a></li>
                                                            
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Footers</a>
                                                        <ul>
                                                            <li><a href="footer1.html">Footer Version 1</a></li>
                                                            
                                                        </ul>
                                                    </li>
                                                    <li><a href="product.html">Product</a></li>
                                                    <li><a href="cart.html">Cart</a></li>
                                                    <li><a href="category.html">Category</a>
                                                        <ul>
                                                            <li><a href="category-list.html">Category list</a></li>
                                                            
                                                        </ul>
                                                    </li>
                                                    <li><a href="blog.html">Blog</a>
                                                        <ul>
                                                            <li><a href="blog.html">Right Sidebar</a></li>
                                                           
                                                        </ul>
                                                    </li>
                                                    <li><a href="checkout.html">Checkout</a></li>
                                                    <li><a href="aboutus.html">About Us</a></li>
                                                    <li><a href="register-account.html">Register Account</a></li>
                                                    <li><a href="compare-products.html">Compare Products</a></li>
                                                    <li><a href="login.html">Login</a></li>
                                                    <li><a href="404.html">404 Page</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Portfolio</a>
                                                <ul>
                                                    <li><a href="#">Classic</a>
                                                        <ul>
                                                            <li><a href="portfolio-2.html">Two Columns</a></li>
                                                            <li><a href="portfolio-3.html">Three Columns</a></li>
                                                            <li><a href="portfolio-4.html">Four Columns</a></li>
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Masonry</a>
                                                        <ul>
                                                            <li><a href="portfolio-masonry-2.html">Two Columns</a></li>
                                                            <li><a href="portfolio-masonry-3.html">Three Columns</a></li>
                                                            <li><a href="portfolio-masonry-4.html">Four Columns</a></li>
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Portfolio Posts</a>
                                                        <ul>
                                                            <li><a href="single-portfolio.html">Image Post</a></li>
                                                            <li><a href="single-portfolio-gallery.html">Gallery Post</a></li>
                                                            <li><a href="single-portfolio-video.html">Video Post</a></li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Elements</a>
                                                <ul>
                                                    <li><a href="elements/tabs.html">Tabs</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact Us</a></li>
                                        </ul>
                                        </nav>
                                    </div><!-- End #menu-right-side -->
                                </div><!-- End #menu-wrapper -->
                            </div><!-- End .col-md-12 -->
                        </div><!-- End .row -->
                    </div><!-- End .container -->
                    
                </div><!-- End #nav -->
            </div><!-- End #inner-header -->
    	</header><!-- End #header -->
		
        <section id="content">
        	<div id="breadcrumb-container">
                    <div class="container">
                        <ul class="breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li class="active">Header</li>
                        </ul>
                    </div>
        	</div>
        	<div class="container">
                    <?php echo $this->content; ?>
                </div><!-- End .container -->
        </section><!-- End #content -->
        
        <footer id="footer">
            <div id="twitterfeed-container">
                <div class="container">
                    <div class="row">
                        <div class="twitterfeed col-md-12">
                            <div class="twitter-icon"><i class="fa fa-twitter"></i></div><!-- End .twitter-icon -->
                            <div class="row">
                                <div class="col-md-10 col-sm-10 col-xs-10 col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
                                    
                                </div>
                            </div>
                        </div><!-- End .twiitterfeed .col-md-12 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End #twitterfeed-container -->
            <div id="inner-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-4 col-xs-12 widget">
                            <h3>MY ACCOUNT</h3>
                            <ul class="links">
                                <li><a href="#">My account</a></li>
                                <li><a href="#">Personal information</a></li>
                                <li><a href="#">Addresses</a></li>
                                <li><a href="#">Discount</a></li>
                                <li><a href="#">Order History</a></li>
                                <li><a href="#">Your Vouchers</a></li>
                            </ul>
                        </div><!-- End .widget -->
                        
                        <div class="col-md-3 col-sm-4 col-xs-12 widget">
                            <h3>INFORMATION</h3>
                            <ul class="links">
                                <li><a href="#">New products</a></li>
                                <li><a href="#">Top sellers</a></li>
                                <li><a href="#">Specials</a></li>
                                <li><a href="#">Manufacturers</a></li>
                                <li><a href="#">Suppliers</a></li>
                                <li><a href="#">Our stores</a></li>
                            </ul>
                        </div><!-- End .widget -->
                        
                        <div class="col-md-3 col-sm-4 col-xs-12 widget">
                            <h3>MY ACCOUNT</h3>
                            
                            <ul class="contact-list">
                                <li><strong>Venedor Ltd</strong></li>
                                <li>United Kingdom</li>
                                <li>Greater London</li>
                                <li>London 02587</li>
                                <li>Oxford Street 48/188</li>
                                <li>Working Days: Mon. - Sun.</li>
                                <li>Working Hours: 9.00AM - 8.00PM</li>
                            </ul>
                        </div><!-- End .widget -->
                        
                        <div class="clearfix visible-sm"></div>
                        
                        <div class="col-md-3 col-sm-12 col-xs-12 widget">
                            <h3>FACEBOOK LIKE BOX</h3>
                            
                            <div class="facebook-likebox">
                                <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fenvato&amp;colorscheme=dark&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false"></iframe>
                            </div>
                        </div><!-- End .widget -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            
            </div><!-- End #inner-footer -->
            
            <div id="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 col-sm-7 col-xs-12 footer-social-links-container">
                            <ul class="social-links clearfix">
                                <li><a href="#" class="social-icon icon-facebook"></a></li>
                                <li><a href="#" class="social-icon icon-twitter"></a></li>
                                <li><a href="#" class="social-icon icon-rss"></a></li>
                                <li><a href="#" class="social-icon icon-delicious"></a></li>
                                <li><a href="#" class="social-icon icon-linkedin"></a></li>
                                <li><a href="#" class="social-icon icon-flickr"></a></li>
                                <li><a href="#" class="social-icon icon-skype"></a></li>
                                <li><a href="#" class="social-icon icon-email"></a></li>
                            </ul>
                        </div><!-- End .col-md-7 -->
                        <div class="col-md-5 col-sm-5 col-xs-12 footer-text-container">
                            <p>&copy; 2016 Powered by EvoMaster&trade;. All Rights Reserved.</p>
                        </div><!-- End .col-md-5 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End #footer-bottom -->
            
        </footer><!-- End #footer -->
    </div><!-- End #wrapper -->
    
    <?php
    echo $this->headScript()
                ->appendFile($this->basePath().'/js/bootstrap.min.js')
                ->appendFile($this->basePath().'/js/smoothscroll.js')
                ->appendFile($this->basePath().'/js/jquery.debouncedresize.js')
                ->appendFile($this->basePath().'/js/retina.min.js')
                ->appendFile($this->basePath().'/js/jquery.placeholder.js')
                ->appendFile($this->basePath().'/js/jquery.hoverIntent.min.js')
                ->appendFile($this->basePath().'/js/twitter/jquery.tweet.min.js')
                ->appendFile($this->basePath().'/js/jquery.flexslider-min.js')
                ->appendFile($this->basePath().'/js/owl.carousel.min.js')
                ->appendFile($this->basePath().'/js/jflickrfeed.min.js')
                ->appendFile($this->basePath().'/js/jquery.prettyPhoto.js')
                ->appendFile($this->basePath().'/js/jquery.fitvids.js')
                ->appendFile($this->basePath().'/js/colpick.js')
                ->appendFile($this->basePath().'/js/modernizr.custom.js') 
                ->appendFile($this->basePath().'/js/jquery.elastislide.js')
                ->appendFile($this->basePath().'/js/jquery.elevateZoom.min.js')
                ->appendFile($this->basePath().'/js/main.js')
            
            ;
    
    ?>
    
</html>