<?php
echo $this->doctype();
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
?>
<!--[if IE 8]> <html class="ie8"> <![endif]-->
<!--[if IE 9]> <html class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title>EvoMaster</title>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('keywords', 'tegnologia,outlet')
                ->appendName('description', 'Tienda online de productos tecnologicos a bajos precios')
        ?>
        <!--[if IE]> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <![endif]-->
        
        <?php
        echo $this->headLink(array('rel' => 'stylesheet', 'href' => 'http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic%7CPT+Gudea:400,700,400italic%7CPT+Oswald:400,700,300','id'=>'googlefont'),'APPEND')
                ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/css/prettyPhoto.css')
                ->appendStylesheet($this->basePath() . '/css/revslider.css')
                ->appendStylesheet($this->basePath() . '/css/owl.carousel.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.selectbox.css')
                ->appendStylesheet($this->basePath() . '/css/style.css')
                ->appendStylesheet($this->basePath() . '/css/responsive.css')
                ->appendStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/toastr/toastr.css?1401216363')
                ->appendStylesheet($this->basePath() . '/admin/assets/css/theme-default/libs/select2/select2.css?1401216370')
                //->appendStylesheet($this->basePath() . '/images/icons/icon.png', 'image/png', '', array('rel'=>'icon'))
                //->appendStylesheet($this->basePath() . '/images/icons/apple-icon-57x57.png', 'image/png', '', array('rel'=>'apple-touch-icon','sizes='=>'57x57'))
                //->appendStylesheet($this->basePath() . '/images/icons/apple-icon-72x72.png', 'image/png', '', array('rel'=>'apple-touch-icon','sizes='=>'72x72'))
                
        ?>
               
        <!--- jQuery -->
        <?php
        echo $this->headScript()
                ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js');
        ?>
        <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
        <script>window.jQuery || document.write('<script src="<?php echo $this->basePath()?>/js/jquery-2.22.2.min.js"><\/script>')</script>

		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->
	    
		<style id="custom-style">
		
		</style>
        <!-- END -->
    
    </head>
    <body>
    <div id="wrapper">
    	<header id="header">
            <div id="header-top">
               <div class="container">
                  <div class="row">
                     <div class="col-md-12">
                        <div class="header-top-left">
                           <ul id="top-links" class="clearfix">
                              <li><a href="#" title="My Wishlist"><span class="top-icon top-icon-pencil"></span><span class="hide-for-xs">My Wishlist</span></a></li>
                              <li><a href="#" title="My Account"><span class="top-icon top-icon-user"></span><span class="hide-for-xs">My Account</span></a></li>
                              <li><a href="cart.html" title="My Cart"><span class="top-icon top-icon-cart"></span><span class="hide-for-xs">My Cart</span></a></li>
                              <li><a href="checkout.html" title="Checkout"><span class="top-icon top-icon-check"></span><span class="hide-for-xs">Checkout</span></a></li>
                           </ul>
                        </div>
                        <!-- End .header-top-left -->
                        <div class="header-top-right">
                           
                           <!-- End .header-top-dropdowns -->
                           <div class="header-text-container pull-right">
                              <p class="header-text">Welcome to Venedor!</p>
                              <?php 
                                    if (isset($_SESSION['user']['username'])) {
                                        echo "<p class='header-link'>".$_SESSION['user']['username']."</p>"
                                                . "<button type='button' class='btn fa fa-sign-out' onclick=\"$(location).attr('href','".str_replace("/public", "", $this->basePath())."/longout')\">Salir</button>";
                                    }
                                    else
                                    {
                                        echo " <p class='header-link'><a href='".str_replace("/public", "", $this->basePath())."/login'>login</a>&nbsp;or&nbsp;<a href='".str_replace("/public", "", $this->basePath())."/singup'>create an account</a></p>";
                                    }
                              ?>
                           </div>
                           <!-- End .pull-right -->
                        </div>
                        <!-- End .header-top-right -->
                     </div>
                     <!-- End .col-md-12 -->
                  </div>
                  <!-- End .row -->
               </div>
               <!-- End .container -->
            </div>
            <!-- End #header-top -->
            <div id="inner-header">
               <div class="container">
                  <div class="row">
                     <div class="col-md-5 col-sm-5 col-xs-12 logo-container">
                        <h1 class="logo clearfix">
                           <span>Responsive eCommerce Template</span>
                           <a href="<?php echo str_replace("/public",'', $this->basePath()) ?>/" title="Venedor eCommerce Template"><img src="<?php echo $this->basePath() ?>/images/logo.png" alt="Venedor Commerce Template" width="238" height="76"></a>
                        </h1>
                     </div>
                     <!-- End .col-md-5 -->
                     <div class="col-md-7 col-sm-7 col-xs-12 header-inner-right">
                        <div class="header-box contact-infos pull-right">
                           <ul>
                              <li><span class="header-box-icon header-box-icon-skype"></span>venedor_support</li>
                              <li><span class="header-box-icon header-box-icon-email"></span><a href="mailto:venedor@gmail.com">venedor@gmail.com</a></li>
                           </ul>
                        </div>
                        <!-- End .contact-infos -->
                        <div class="header-box contact-phones pull-right clearfix">
                           <span class="header-box-icon header-box-icon-earphones"></span>
                           <ul class="pull-left">
                              <li>+(404) 158 14 25 78</li>
                              <li>+(404) 851 21 48 15</li>
                           </ul>
                        </div>
                        <!-- End .contact-phones -->
                     </div>
                     <!-- End .col-md-7 -->
                  </div>
                  <!-- End .row -->
               </div>
               <!-- End .container -->
               <div id="main-nav-container">
                  <div class="container">
                     <div class="row">
                        <div class="col-md-12 clearfix">
                           <nav id="main-nav">
                              <div id="responsive-nav">
                                 <div id="responsive-nav-button">
                                    Menu <span id="responsive-nav-button-icon"></span>
                                 </div>
                                 <!-- responsive-nav-button -->
                              </div>
                              <ul class="menu clearfix">
                                 <li>
                                     <a class="active" href="<?php echo str_replace("/public", "",$this->basePath()) ?>">HOME</a>
                                 </li>
                                 <li class="mega-menu-container">
                                    <a href="#">Tienda</a>
                                    <div class="mega-menu clearfix">
                                       <div class="col-5">
                                          <a href="category.html" class="mega-menu-title">Clothing</a><!-- End .mega-menu-title -->
                                          <ul class="mega-menu-list clearfix">
                                             <li><a href="#">Dresses</a></li>
                                          </ul>
                                       </div>
                                       <!-- End .col-5 -->
                                       <div class="col-5">
                                          <a href="category.html" class="mega-menu-title">Shoes</a><!-- End .mega-menu-title -->
                                          <ul class="mega-menu-list clearfix">
                                             <li><a href="#">Formal Shoes</a></li>
                                          </ul>
                                       </div>
                                       <!-- End .col-5 -->
                                       <div class="col-5">
                                          <a href="category.html" class="mega-menu-title">Accessories</a><!-- End .mega-menu-title -->
                                          <ul class="mega-menu-list clearfix">
                                             <li><a href="#">Bags &amp; Purses</a></li>
                                          </ul>
                                       </div>
                                       <!-- End .col-5 -->
                                       <div class="col-5">
                                          <a href="category.html" class="mega-menu-title">Sports</a><!-- End .mega-menu-title -->
                                          <ul class="mega-menu-list clearfix">
                                             <li><a href="#">Sport Tops &amp; Vests</a></li>
                                          </ul>
                                       </div>
                                       <!-- End .col-5 -->
                                       <div class="col-5">
                                          <a href="category.html" class="mega-menu-title">Maternity</a><!-- End .mega-menu-title -->
                                          <ul class="mega-menu-list clearfix">
                                             <li><a href="#">Tops &amp; Skirts</a></li>
                                          </ul>
                                       </div>
                                       <!-- End .col-5 -->
                                    </div>
                                    <!-- End .mega-menu -->
                                 </li>
                                 <li>
                                    <a href="#">Noticias</a>
                                    <ul>
                                       <li>
                                          <a href="#">Headers</a>
                                          <ul>
                                             <li><a href="header1.html">Header Version 1</a></li>
                                          </ul>
                                       </li>
                                       <li>
                                          <a href="#">Footers</a>
                                          <ul>
                                             <li><a href="footer1.html">Footer Version 1</a></li>
                                          </ul>
                                       </li>
                                       <li><a href="product.html">Product</a></li>
                                       <li><a href="cart.html">Cart</a></li>
                                       <li>
                                          <a href="category.html">Category</a>
                                          <ul>
                                             <li><a href="category-list.html">Category list</a></li>
                                          </ul>
                                       </li>
                                       <li>
                                          <a href="blog.html">Blog</a>
                                          <ul>
                                             <li><a href="blog.html">Right Sidebar</a></li>
                                          </ul>
                                       </li>
                                       <li><a href="checkout.html">Checkout</a></li>
                                    </ul>
                                 </li>
                                 <li>
                                    <a href="#">Portfolio</a>
                                    <ul>
                                       <li>
                                          <a href="#">Classic</a>
                                          <ul>
                                             <li><a href="portfolio-2.html">Two Columns</a></li>
                                          </ul>
                                       </li>
                                       <li>
                                          <a href="#">Masonry</a>
                                          <ul>
                                             <li><a href="portfolio-masonry-2.html">Two Columns</a></li>
                                          </ul>
                                       </li>
                                       <li>
                                          <a href="#">Portfolio Posts</a>
                                          <ul>
                                             <li><a href="single-portfolio.html">Image Post</a></li>
                                          </ul>
                                       </li>
                                    </ul>
                                 </li>
                                 <li>
                                    <a href="#">Lista de Precios</a>
                                 </li>
                                 <li><a href="<?php echo $this->basePath()?>/contactanos">Contactenos</a></li>
                              </ul>
                           </nav>
                           <div id="quick-access">
                              <div class="dropdown-cart-menu-container pull-right">
                                 <div class="btn-group dropdown-cart">
                                    <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown">
                                    <span class="cart-menu-icon"></span>
                                    0 item(s) <span class="drop-price">- $0.00</span>
                                    </button>
                                    <div class="dropdown-menu dropdown-cart-menu pull-right clearfix" role="menu">
                                       <p class="dropdown-cart-description">Recently added item(s).</p>
                                       <ul class="dropdown-cart-product-list">
                                          <li class="item clearfix">
                                             <a href="#" title="Delete item" class="delete-item"><i class="fa fa-times"></i></a>
                                             <a href="#" title="Edit item" class="edit-item"><i class="fa fa-pencil"></i></a>
                                             <figure>
                                                <a href="product.html"><img src="<?php echo $this->basePath() ?>/images/products/thumbnails/item12.jpg" alt="phone 4"></a>
                                             </figure>
                                             <div class="dropdown-cart-details">
                                                <p class="item-name">
                                                   <a href="product.html">Cam Optia AF Webcam </a>
                                                </p>
                                                <p>
                                                   1x
                                                   <span class="item-price">$499</span>
                                                </p>
                                             </div>
                                             <!-- End .dropdown-cart-details -->
                                          </li>
                                       </ul>
                                       <ul class="dropdown-cart-total">
                                          <li><span class="dropdown-cart-total-title">Shipping:</span>$7</li>
                                          <li><span class="dropdown-cart-total-title">Total:</span>$1005<span class="sub-price">.99</span></li>
                                       </ul>
                                       <!-- .dropdown-cart-total -->
                                       <div class="dropdown-cart-action">
                                          <p><a href="cart.html" class="btn btn-custom-2 btn-block">Cart</a></p>
                                          <p><a href="checkout.html" class="btn btn-custom btn-block">Checkout</a></p>
                                       </div>
                                       <!-- End .dropdown-cart-action -->
                                    </div>
                                    <!-- End .dropdown-cart -->
                                 </div>
                                 <!-- End .btn-group -->
                              </div>
                              <!-- End .dropdown-cart-menu-container -->
                              <form class="form-inline quick-search-form" role="form" method="get" name="bla"  action="<?php echo str_replace("/public","", $this->basePath()) ?>/buscar">
                                 <div class="form-group">
                                     <input type="text" name="textobusqueda" id="textobusqueda" class="form-control" placeholder="Buscar en la tienda">
                                 </div>
                                 <!-- End .form-inline -->
                                 <button type="submit" id="quick-search" class="btn btn-custom"></button>
                              </form>
                           </div>
                           <!-- End #quick-access -->
                        </div>
                        <!-- End .col-md-12 -->
                     </div>
                     <!-- End .row -->
                  </div>
                  <!-- End .container -->
               </div>
               <!-- End #nav -->
            </div>
            <!-- End #inner-header -->
         </header>
<!-- End #header -->
		
        <section id="content">
        	<div id="breadcrumb-container">
                    <div class="container">
                        <ul class="breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li class="active">Header</li>
                        </ul>
                    </div>
        	</div>
        	<div class="container">
                    <?php echo $this->content; ?>
                </div><!-- End .container -->
                <!-- Fabricantes -->
                <div id="brand-slider-container" class="carousel-wrapper">
                    <header class="content-title">
                       <div class="title-bg">
                          <h2 class="title"></h2>
                       </div>
                       <!-- End .title-bg -->
                    </header>
                    <div class="carousel-controls">
                       <div id="brand-slider-prev" class="carousel-btn carousel-btn-prev">
                       </div>
                       <!-- End .carousel-prev -->
                       <div id="brand-slider-next" class="carousel-btn carousel-btn-next carousel-space">
                       </div>
                       <!-- End .carousel-next -->
                    </div>
                    <!-- End .carousel-controllers -->
                    <div class="sm-margin"></div>
                    <!-- space -->
                    <div class="row">
                       <div class="brand-slider owl-carousel">
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/1-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/2-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/3-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/4-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/5-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/6-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/7-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/8-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/9-brand.jpg"></a>
                          <a><img src="<?php echo $this->basePath() ?>/images/brands/10-brand.jpg"></a>
                       </div>
                       <!-- End .brand-slider -->
                    </div>
                    <!-- End .row -->
                </div>
                 
        </section><!-- End #content -->
        
        <footer id="footer">
            
            <div id="twitterfeed-container">
                <div class="container">
                    <div class="row">
                        <div class="twitterfeed col-md-12">
                            <div class="twitter-icon"><i class="fa fa-twitter"></i></div><!-- End .twitter-icon -->
                            <div class="row">
                                <div class="col-md-10 col-sm-10 col-xs-10 col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
                                    
                                </div>
                            </div>
                        </div><!-- End .twiitterfeed .col-md-12 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End #twitterfeed-container -->
            <div id="inner-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-4 col-xs-12 widget">
                            <h3>MY ACCOUNT</h3>
                            <ul class="links">
                                <li><a href="#">My account</a></li>
                                <li><a href="#">Personal information</a></li>
                                <li><a href="#">Addresses</a></li>
                                <li><a href="#">Discount</a></li>
                                <li><a href="#">Order History</a></li>
                                <li><a href="#">Your Vouchers</a></li>
                            </ul>
                        </div><!-- End .widget -->
                        
                        <div class="col-md-3 col-sm-4 col-xs-12 widget">
                            <h3>INFORMATION</h3>
                            <ul class="links">
                                <li><a href="#">New products</a></li>
                                <li><a href="#">Top sellers</a></li>
                                <li><a href="#">Specials</a></li>
                                <li><a href="#">Manufacturers</a></li>
                                <li><a href="#">Suppliers</a></li>
                                <li><a href="#">Our stores</a></li>
                            </ul>
                        </div><!-- End .widget -->
                        
                        <div class="col-md-3 col-sm-4 col-xs-12 widget">
                            <h3>MY ACCOUNT</h3>
                            
                            <ul class="contact-list">
                                <li><strong>Venedor Ltd</strong></li>
                                <li>United Kingdom</li>
                                <li>Greater London</li>
                                <li>London 02587</li>
                                <li>Oxford Street 48/188</li>
                                <li>Working Days: Mon. - Sun.</li>
                                <li>Working Hours: 9.00AM - 8.00PM</li>
                            </ul>
                        </div><!-- End .widget -->
                        
                        <div class="clearfix visible-sm"></div>
                        
                        <div class="col-md-3 col-sm-12 col-xs-12 widget">
                            <h3>FACEBOOK LIKE BOX</h3>
                            
                            <div class="facebook-likebox">
                                <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fenvato&amp;colorscheme=dark&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false"></iframe>
                            </div>
                        </div><!-- End .widget -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            
            </div><!-- End #inner-footer -->
            
            <div id="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 col-sm-7 col-xs-12 footer-social-links-container">
                            <ul class="social-links clearfix">
                                <li><a href="#" class="social-icon icon-facebook"></a></li>
                                <li><a href="#" class="social-icon icon-twitter"></a></li>
                                <li><a href="#" class="social-icon icon-rss"></a></li>
                                <li><a href="#" class="social-icon icon-delicious"></a></li>
                                <li><a href="#" class="social-icon icon-linkedin"></a></li>
                                <li><a href="#" class="social-icon icon-flickr"></a></li>
                                <li><a href="#" class="social-icon icon-skype"></a></li>
                                <li><a href="#" class="social-icon icon-email"></a></li>
                            </ul>
                        </div><!-- End .col-md-7 -->
                        <div class="col-md-5 col-sm-5 col-xs-12 footer-text-container">
                            <p>&copy; 2016 Powered by EvoMaster&trade;. All Rights Reserved.</p>
                        </div><!-- End .col-md-5 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End #footer-bottom -->
            
        </footer><!-- End #footer -->
    </div><!-- End #wrapper -->
    
    <?php
    echo $this->headScript()
                ->appendFile($this->basePath().'/js/bootstrap.min.js')
                ->appendFile($this->basePath().'/js/smoothscroll.js')
                ->appendFile($this->basePath().'/js/jquery.debouncedresize.js')
                ->appendFile($this->basePath().'/js/retina.min.js')
                ->appendFile($this->basePath().'/js/jquery.placeholder.js')
                ->appendFile($this->basePath().'/js/jquery.hoverIntent.min.js')
                ->appendFile($this->basePath().'/js/twitter/jquery.tweet.min.js')
                ->appendFile($this->basePath().'/js/jquery.flexslider-min.js')
                ->appendFile($this->basePath().'/js/owl.carousel.min.js')
                ->appendFile($this->basePath().'/js/jflickrfeed.min.js')
                ->appendFile($this->basePath().'/js/jquery.prettyPhoto.js')
                ->appendFile($this->basePath().'/js/jquery.fitvids.js')
                ->appendFile($this->basePath().'/js/colpick.js')
                ->appendFile($this->basePath().'/js/modernizr.custom.js') 
                ->appendFile($this->basePath().'/js/jquery.elastislide.js')
                ->appendFile($this->basePath().'/js/jquery.elevateZoom.min.js')
            
                ->appendFile($this->basePath().'/js/jquery.themepunch.tools.min.js')
                ->appendFile($this->basePath().'/js/jquery.themepunch.revolution.min.js')
                ->appendFile($this->basePath().'/js/jquery.jscrollpane.min.js')
            
                ->appendFile($this->basePath().'/js/main.js')
                ->appendFile($this->basePath().'/js/jquery.selectbox.min.js') 
                ->appendFile($this->basePath().'/admin/assets/js/libs/toastr/toastr.min.js') 
                ->appendFile($this->basePath().'/js/customScript.js')
                
            
                
            
            ;
    
    ?>
     
</html>