<?php
$form=$this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) 
{
    echo "<script type='text/javascript'>".$this->msg."</script>";    
}
if ($this->numeroPedido != null) {
    echo "<script type='text/javascript'>showMessageSuccess('Número Pedido Compra','Se genero el pedido con el numero ".$this->numeroPedido."');</script>";
}
?>
<script type="text/javascript">
    var numRows=0;

    function AddRow()
    {
        numRows++;
        var onClick="onclick=\"if($('#idProveedor').val() == '') showMessaginfo('','Favor seleccionar el Proveedor'); else showBusquedaOnModal(this,'<?php echo $this->basePath()?>/admin/producto/buscar?campoId=idProducto"+numRows+"&campoNombre=nombreProducto"+numRows+"','')\"";
        var cadena ="<tr id='pedidoCompraPosicion"+numRows+"'>";
        cadena += "<td>"+numRows+"</td>";
        cadena += " <td><div class='col-lg-8 col-md-4 col-sm-4'>";
        cadena += "<input class='form-control' id='idProducto"+numRows+"' name='idProducto"+numRows+"' type='hidden'>";
        cadena += "<input class='form-control' id='nombreProducto"+numRows+"' type='text' required='required' onkeypress='return false'></div>";
        cadena += "<input type='button' "+onClick+" data-target='#textModal' data-toggle='modal' style='margin:2px' class='btn btn-support2' value='Buscar'></td>";
        cadena += "<td><input name=\"cantidad"+numRows+"\" id=\"cantidad"+numRows+"\" type='text' required='required' placeholder='cantidad' maxlength='9' class='form-control' onkeypress=\"return validarTecla(event,'num')\"></td>";
        cadena += "<td><input name=\"valorCompra"+numRows+"\" id=\"valorCompra"+numRows+"\" type='text' required='required' placeholder='Valor Compra' maxlength='9' class='form-control' onkeypress=\"return validarTecla(event,'num')\"></td>";
        cadena += "<td><a class='btn btn-danger' onclick=\"$('#pedidoCompraPosicion"+numRows+"').remove()\"><i class='fa  fa-minus-square'></i></a></td></tr>";
        $('#tBodyPedido').append(cadena);
    }
    $(document).ready(function() {
        AddRow();
        // Valida que el formulario no tenga ningun detalle con productos repeditos
        $("#<?php echo $form->getName()?>").submit(function( event ) {
            var productos = []
            $("#<?php echo $form->getName()?>").find("input[name^='idProducto']").each(function() {
                if (jQuery.inArray(productos[0], $(this).val() )>-1) 
                {
                    showMessageWarning('Productos Repetidos','En el detalle del pedido no se puede adicionar mas de una vez un producto')
                    event.preventDefault();
                    return;
                }
                productos.push($(this).val());
            });
        });
    });
</script>
 
<div class="row">
    <div class="col-lg-12">
        <div class="box box-bordered style-primary">
            <div class="box-head">
                <header>
                    <h4 class="text-light">
                        <i class="fa fa-fw fa-laptop"></i> Solicitud <strong>Pedido Compra</strong>
                    </h4>
                    
                </header>
                <!--
                <div class="tools">
                    <div class="btn-group btn-group-transparent">
                        <a class="btn btn-equal btn-sm " data-target="#textModal" data-toggle="modal" onclick="usar_ajax('<?php echo $this->basePath()?>/admin/pedidocompra/buscar','#modal-dialog-display','')"><i class="fa  fa-search"></i></a>
                        <!--<a class="btn btn-equal btn-sm btn-collapse"><i class="fa fa-angle-down"></i></a>
                    </div>
                </div>-->
            </div>
            <!--
            <div class="box-body style-white" style="display: none;">
                <div class="col-md-1">
                    <a href="#" class="btn btn-default  btn-labeled">
                        <span><i class="fa fa-envelope"></i></span>
                    </a>
                </div>
            </div>
            -->
        </div>
    </div>
    <div class="col-lg-12">
        
        <div class="box">
            
            <div class="box-body">
                <?php echo $this->form()->openTag($form);
                      echo $this->formElement($form->get('idProveedor'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Proveedor</label>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-5">
                            <?php echo $this->formInput($form->get('nombreProveedor'));?>  
                            
                        </div>
                        <?php echo $this->formElement($form->get('btnBuscarProveedor'));?>  
                    </div>
                    <div class="row">
        
                        <div class="col-lg-12">
                                <div class="box box-outlined style-primary1">
                                    <div class="box-head">
                                        <header><h4 class="text-light"><i class="fa fa-fw  fa-list"></i> Pedido <strong>Detalle</strong></h4></header>
                                        <div class="tools">
                                            <div class="btn-group btn-group-transparent">
                                                <a class="btn btn-equal btn-sm " onclick="AddRow()" title="Agregar nuevo detalle"><i class="fa fa-plus"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="box-body" style="display: block;">
                                        <div class="table-responsive no-margin">
                                            <table class="table table-striped no-margin">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Producto</th>
                                                        <th>Cantidad</th>
                                                        <th>Valor Compra</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody id="tBodyPedido">
                                                    <!--  -->
                                                </tbody>
                                            </table>
                                    </div>
                                    </div>
                                </div>
                        </div><!--end .col-lg-6 -->
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <?php echo $this->formElement($form->get('btnGuardar'));?>  
                        <?php echo $this->formElement($form->get('btnCancelar'));?> 
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
    </div><!--end .col-lg-12 -->
    
</div>