<?php $parametrosGet = "&botonClose=".$this->botonClose."&contenedorDialog=".$this->contenedorDialog."&modal=".$this->modal; ?>
<script type="text/javascript">
    $(document).ready(function () {
        $('#dtbuscarCliente').DataTable();
        LimpiarModal('<?php echo $this->botonClose ?>','<?php echo $this->contenedorDialog ?>','<?php echo $this->modal ?>');
    });
</script>
<div class="row">  
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" id="<?php echo $this->botonClose ?>" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="textModalLabel"><h4 class="text-light">Búsqueda de <strong>Cliente</strong></h4></h4>
        </div>
        <div class="box-body">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-group">
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Nit</label>
                </div>
                <div class="col-lg-3 col-md-11 col-sm-9">
                     <?php echo $this->formElement($form->get('nit'));?>                            
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-lg-1 col-md-2 col-sm-3">
                    <label for="email1" class="control-label">Descripción</label>
                </div>
                <div class="col-lg-3 col-md-11 col-sm-9">
                     <?php echo $this->formElement($form->get('descripcion'));?>                            
                </div>
            </div>

            <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                <input name="btnBuscar" id="btnBuscar" type="button" title="Buscar" style="margin:2px" class="btn btn-success" value="Buscar" 
                       onclick="usar_ajax('<?php echo $this->basePath()?>/admin/cliente/buscar?campoId=<?php echo $this->campoId ?>&campoNombre=<?php echo $this->campoNombre ?><?php echo $parametrosGet ?> ','#<?php echo $this->contenedorDialog ?>','nit='+$('#nit').val()+'&amp;descripcion='+$('#descripcion').val());">
                <?php
                    echo $this->formElement($form->get('btnCancelar'));
                ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        
        <div class="box "> 
            <div class="box-body table-responsive">
                <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                    <table id="dtbuscarCliente" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                        <thead>
                            <tr role="row">
                                <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Tercero</th>
                                <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Municipio</th>
                                <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Email</th>
                            </tr>
                        </thead>
                        <tbody>
                             <?php 
                            foreach ($this->registros as $obj) {
                                echo "
                                    <tr class='gradeX odd' style='cursor:pointer' onClick=\"$('#".$this->campoId."').val(".$obj['idCliente'].");$('#".$this->campoNombre."').val('".$obj["descripcionTercero"]."');$('#". $this->botonClose ."').click();\">
                                        <td>".$obj['descripcionTercero']."</td>
                                        <td>".$obj['descripcionMunicipio']."</td>
                                        <td>".$obj['email']."</td>
                                    </tr>";
                            }
                            ?>
                        </tbody>
                    </table>
                 </div>
            </div>
        </div>
    </div>
</div>
    

 