<script type="text/javascript">
$(document).ready(function(){
    
    //$("a[rel^='prettyPhoto']").prettyPhoto();
    //$( '#product-carousel' ).elastislide({orientation : 'horizontal',});
    /*$( '#product-carousell' ).elastislide( {
            orientation : 'vertical'
    } );*/
    
  });
</script>
<div class="row">
   <div class="col-md-12">
      <div class="row">
         <div class="col-md-6 col-sm-12 col-xs-12 product-viewer clearfix">
            <div id="product-image-carousel-container">
               <ul id="product-carousel" class="celastislide-list" style="height: 556px;">
                   <?php 
                   $class = "class='active-slide'";
                   foreach ($this->imagenesProducto  as $imagen)
                   {
                       echo "<li $class><a data-rel='prettyPhoto[product]' href='".$imagen['url']."' data-image='".$imagen['url']."' data-zoom-image='".$imagen['url']."'><img src='".$imagen['url']."' alt='Phone photo 2'></a></li>";
                       $class = "";
                   }
                   ?>
               </ul>
            </div>
            <div id="product-image-container">
               <figure>
                  <img src="<?php echo $this->imagenesProducto[0]['url'] ?>" data-zoom-image="<?php echo $this->imagenesProducto[0]['url'] ?>" alt="" id="product-image">
                  <figcaption class="item-price-container">
                      <?php 
                        if(isset($this->Producto['idPromocion']))
                        {
                            echo "<span class='old-price'>$".number_format($this->Producto['valorAnterior'])."</span>
                                 <span class='item-price'>$".number_format($this->Producto['valorPromocion'])."</span>";
                        }
                        else
                        {
                             echo "<span class='item-price'>$".number_format($this->Producto['valorVenta'])."</span>";
                        }
                      ?>
                  </figcaption>
               </figure>
            </div>
         </div>
         <div class="col-md-6 col-sm-12 col-xs-12 product">
            <div class="lg-margin visible-sm visible-xs"></div>
            <h1 class="product-name"><?php echo $this->Producto['nombre']?></h1>
            <div class="ratings-container">
               <div class="ratings separator">
                  <div class="ratings-result" data-result="100"></div>
               </div>
               <span class="ratings-amount separator">
               3 Review(s)
               </span>
               <span class="separator">|</span>
               <a href="#review" class="rate-this">Add Your Review</a>
            </div>
            <ul class="product-list">
               <li><span>Referencia:</span><?php echo $this->Producto['referencia']?></li>
               <li><span>Availability:</span>In Stock</li>
               <li><span>Código Producto:</span><?php echo $this->Producto['codigo']?></li>
               <li><span>Marca:</span><?php echo $this->Producto['descripcionMarca']?></li>
            </ul>
            
            <!--
            <div class="product-color-filter-container">
               <span>Select Color:</span>
               <div class="xs-margin"></div>
               <ul class="filter-color-list clearfix">
                  <li><a href="#" data-bgcolor="#fff" class="filter-color-box"></a></li>
                  <li><a href="#" data-bgcolor="#d1d2d4" class="filter-color-box"></a></li>
                  <li><a href="#" data-bgcolor="#666467" class="filter-color-box"></a></li>
                  <li><a href="#" data-bgcolor="#515151" class="filter-color-box"></a></li>
                  <li><a href="#" data-bgcolor="#bcdae6" class="filter-color-box"></a></li>
                  <li><a href="#" data-bgcolor="#5272b3" class="filter-color-box"></a></li>
                  <li><a href="#" data-bgcolor="#acbf0b" class="filter-color-box"></a></li>
               </ul>
            </div>-->
            <!-- End .product-color-filter-container-->
            <!--
            <div class="product-size-filter-container">
               <span>Select Size:</span>
               <div class="xs-margin"></div>
               <ul class="filter-size-list clearfix">
                  <li><a href="#">XS</a></li>
                  <li><a href="#">S</a></li>
                  <li><a href="#">M</a></li>
                  <li><a href="#">L</a></li>
                  <li><a href="#">XL</a></li>
               </ul>
            </div>--<
            <!-- End .product-size-filter-container-->
            <hr>
            <div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                <input type="number" class="form-control ui-spinner-input" name="cantidad" id="cantidad" onkeypress="return validarTecla(event,'num')" value="1">
                </div>
                <button class="btn btn-custom-2" 
                        onclick="agregarProductoCart(<?php echo $this->Producto['idSaldoInventario'] ?>,$('#cantidad').val(),'<?php echo $this->BasePath() ?>')">
                        ADD TO CART
                </button>
            </div>
            <div class="md-margin"></div>
            <!-- 
            <div class="product-extra clearfix">
               <div class="product-extra-box-container clearfix">
                  <div class="item-action-inner">
                     <a href="#" class="icon-button icon-like">Favourite</a>
                     <a href="#" class="icon-button icon-compare">Checkout</a>
                  </div>
               </div>
               <div class="md-margin visible-xs"></div>
            </div>
            -->
         </div>
      </div>
      <div class="lg-margin2x"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-primary"> 
                <div class="panel-heading"> 
                    <h3 class="panel-title">DESCRIPCIÓN</h3> 
                </div> 
                <div class="panel-body"> 
                    <?php echo $this->Producto['descripcion']?>
                </div> 
            </div>
            <div class="panel panel-primary"> 
                <div class="panel-heading"> 
                    <h3 class="panel-title">ESPECIFICACIÓN</h3> 
                </div> 
                <div class="panel-body"> 
                    
                    <?php echo $this->Producto['especificacion'];?>
                </div> 
            </div>
            <div class="lg-margin visible-xs"></div>
         </div>
         <div class="lg-margin2x visible-sm visible-xs"></div>
      </div>
      <div class="lg-margin2x"></div>
      <?php 
        if(count($this->productosSimilares)> 0)
        {
      ?>
      <div class="purchased-items-container carousel-wrapper">
         <header class="content-title">
            <div class="title-bg">
               <h2 class="title">También Te podría Interesar</h2>
            </div>
         </header>
         <div class="carousel-controls">
            <div id="purchased-items-slider-prev" class="carousel-btn carousel-btn-prev"></div>
            <div id="purchased-items-slider-next" class="carousel-btn carousel-btn-next carousel-space"></div>
         </div>
         <div class="purchased-items-slider owl-carousel">
             <?php
                foreach ($this->productosSimilares as $producto) 
                {
                    echo "<div class='item item-hover'>
                            <div class='item-image-wrapper'>
                                <figure class='item-image-container'>
                                    <a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>
                                        <img src='".$producto['urlImg']."' alt='item1' class='item-image'>
                                        <img src='".$producto['urlImg']."' alt='item1' class='item-image-hover'>
                                    </a>
                                </figure>";
                    if($producto['idPromocion']!= null)
                    {
                                echo "<div class='item-price-container'> 
                                        <span class='old-price'>$".number_format($producto['valorAnterior'])."</span>
                                        <span class='item-price'>$".number_format($producto['valorPromocion'])."</span>
                                      </div>
                                      <span class='discount-rect'>-".number_format($producto['procentajeDescuento'])."%</span>";
                    }
                    else 
                        echo "<div class='item-price-container'> <span class='item-price'>$".number_format($producto['valorVenta'])."</span></div>";
                    echo  " </div>
                            <div class='item-meta-container'>
                               <div class='ratings-container'>
                                  <div class='ratings'>
                                     <div class='ratings-result' data-result='99'></div>
                                  </div>
                                  <span class='ratings-amount'>
                                  4 Reviews
                                  </span>
                               </div>
                               <h3 class='item-name'><a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>".$producto['nombre']."</a></h3>
                               <div class='item-action'>
                                  <a href='#' class='item-add-btn'>
                                  <span class='icon-cart-text'></i> Add to Cart</span>
                                  </a>
                               </div>
                            </div>
                         </div>";
                }
            ?>            
         </div>
      </div>
      <?php
        }
      ?>
   </div>
</div>
			