 <!--<div id="slider-rev-container">
   <div id="slider-rev">
      <ul>
         <li data-transition="fade" data-slotamount="6" data-masterspeed="600" data-saveperformance="on"  data-title="Special Offers">
            <img src="<?php echo $this->basePath() ?>/public/images/revslider/dummy.png"  alt="slidebg1" data-lazyload="<?php echo $this->basePath() ?>/public/img/The_Division-WMFG-ES.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
            <div class="tp-caption rev-title lfr ltr" data-x="695" data-y="198" data-speed="1600" data-start="300" data-endspeed="300">SPECIAL OFFER -25%</div>
            <div class="tp-caption rev-text lfr ltr" data-x="695" data-y="252" data-speed="1600" data-start="600" data-endspeed="550">Performance &amp; Design. Taken right <br> to the edge.</div>
            <div class="tp-caption lfr ltr" data-x="695" data-y="332" data-speed="1600" data-start="900" data-endspeed="800">
               <a href="#" class="btn btn-custom-2">Learn More</a>
            </div>
            <div class="tp-caption lfl ltl" data-x="center"  data-y="bottom"  data-speed="2000" data-start="500" data-endspeed="800">
               <img src="<?php echo $this->basePath() ?>/public/img/The_Division-WMFG-ES.jpg">
            </div>
         </li>
      </ul>
   </div>
   
</div>-->
<!-- End #slider-rev-container -->
<div class="md-margin2x"></div>
<!-- Space -->
<div class="container">
   <div class="row">
      <div class="col-md-12">
         <div class="row">
            <div class="col-md-12 col-sm-10 col-xs-12 main-content">
            <?php
                // Promociones
                if (count($this->promociones) > 0) 
                {
                    echo "<header class='content-title'>
                            <h2 class='title'>Ofertas Especiales</h2>
                            <p class='title-desc'>Guarda tu tiempo y dinero. En nuestra tienda encontraras ofertas de locura</p>
                         </header>

                        <div id='products-tabs-content' class='row'>";

                            foreach ($this->promociones as $promo) 
                            {
                                echo "<div class='col-md-3 col-sm-6 col-xs-12'>
                                        <div class='item item-hover'>
                                           <div class='item-image-wrapper'
                                              <figure class='item-image-container'>
                                                 <a href='".$this->basePath()."/producto/".$promo['idSaldoInventario']."'>
                                                    <img src='".$promo['urlImg']."' alt='item1' class='item-image'>
                                                 </a>
                                              </figure>
                                              <div class='item-price-container'>
                                                 <span class='old-price'>$".number_format($promo['valorAnterior'])."</span>
                                                 <span class='item-price'>$".number_format($promo['valorPromocion'])."</span>
                                              </div>

                                              <!--<span class='new-rect'>New</span>-->
                                              <span class='discount-rect'>-".number_format($promo['procentajeDescuento'])."%</span>
                                           </div>
                                           <div class='item-meta-container'>
                                              <div class='ratings-container'>
                                                 <div class='ratings'>
                                                    <div class='ratings-result' data-result='100'></div>
                                                 </div>

                                                 <span class='ratings-amount'>
                                                 5 Reviews
                                                 </span>
                                              </div>
                                              <h3 class='item-name'><a href='".$this->basePath()."/producto/".$promo['idSaldoInventario']."'>".$promo['nombre']."</a></h3>
                                              <div class='item-action'>
                                                    <a onclick=\"agregarProductoCart(".$promo['idSaldoInventario'].",1,'".$this->BasePath()."')\" class='item-add-btn'>
                                                       <span class='icon-cart-text'>Add to Cart</span>
                                                    </a>
                                              </div>
                                           </div>
                                        </div>
                                     </div>";
                            }
                    echo "</div>";
                }
                if(count($this->productosNuevos) >0)
                {
                    echo "<header class='content-title'>
                            <h2 class='title'>Productos Nuevos</h2>
                            <p class='title-desc'>Save your money and time with our store. Here's the best part of our impressive assortment.</p>
                          </header>
                          <div id='products-tabs-content' class='row'>";
                    foreach ($this->productosNuevos as $producto) 
                    {
                        echo "<div class='col-md-3 col-sm-6 col-xs-12'>
                                <div class='item item-hover'>
                                    <div class='item-image-wrapper'
                                        <figure class='item-image-container'>
                                           <a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>
                                              <img src='".$producto['urlImg']."' alt='item1' class='item-image'>
                                           </a>
                                        </figure>";
                                if($producto['idPromocion']!= null)
                                {
                                    echo "<div class='item-price-container'> 
                                            <span class='old-price'>$".number_format($producto['valorAnterior'])."</span>
                                            <span class='item-price'>$".number_format($producto['valorPromocion'])."</span>
                                          </div>
                                          <span class='new-rect'>New</span>
                                          <span class='discount-rect'>-".number_format($producto['procentajeDescuento'])."%</span>";
                                }
                                else {
                                    echo "<div class='item-price-container'><span class='item-price'>$".number_format($producto['valorVenta'])."</span></div>
                                    <span class='new-rect'>New</span>";
                                }
                        echo "      </div>
                                    <div class='item-meta-container'>
                                       <div class='ratings-container'>
                                          <div class='ratings'>
                                             <div class='ratings-result' data-result='100'></div>
                                          </div>
                                          <span class='ratings-amount'>
                                          5 Reviews
                                          </span>
                                       </div>
                                       <h3 class='item-name'><a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>".$producto['nombre']."</a></h3>
                                       <div class='item-action'>
                                          <a onclick=\"agregarProductoCart(".$producto['idSaldoInventario'].",1,'".$this->BasePath()."')\" class='item-add-btn'>
                                            <span class='icon-cart-text'>Add to Cart</span>
                                          </a>
                                       </div>
                                    </div>
                                </div>
                             </div>";
                    }
                    echo "</div>";
                }
                ?>
               <div class="xlg-margin"></div>
               <?php 
                    if(count($this->productosMasVendidos) > 0)
                    {
                ?>
               <div class="hot-items carousel-wrapper">
                  <header class="content-title">
                     <div class="title-bg">
                        <h2 class="title">Los Más Vendidos</h2>
                     </div>
                     <p class="title-desc">Only with us you can get a new model with a discount.</p>
                  </header>
                  <div class="carousel-controls">
                     <div id="hot-items-slider-prev" class="carousel-btn carousel-btn-prev">
                     </div>
                     <div id="hot-items-slider-next" class="carousel-btn carousel-btn-next carousel-space">
                     </div>
                  </div>
                  <div class="hot-items-slider owl-carousel">
                    <?php
                        foreach ($this->productosMasVendidos as $producto) 
                        {
                            echo "<div class='item item-hover'>
                                    <div class='item-image-wrapper'>
                                       <figure class='item-image-container'>
                                          <a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>
                                                <img src='".$producto['urlImg']."' alt='item1' class='item-image'>
                                          </a>
                                       </figure>";
                            if($producto['idPromocion']!= null)
                            {
                                        echo "<div class='item-price-container'> 
                                                <span class='old-price'>$".number_format($producto['valorAnterior'])."</span>
                                                <span class='item-price'>$".number_format($producto['valorPromocion'])."</span>
                                              </div>
                                              <span class='discount-rect'>-".number_format($producto['procentajeDescuento'])."%</span>";
                            }
                            else 
                                echo "<div class='item-price-container'> <span class='item-price'>$".number_format($producto['valorVenta'])."</span></div>";
                            echo  " </div>
                                    <div class='item-meta-container'>
                                       <div class='ratings-container'>
                                          <div class='ratings'>
                                             <div class='ratings-result' data-result='99'></div>
                                          </div>
                                          <span class='ratings-amount'>
                                          4 Reviews
                                          </span>
                                       </div>
                                       <h3 class='item-name'><a href='".$this->basePath()."/producto/".$producto['idSaldoInventario']."'>".$producto['nombre']."</a></h3>
                                       <div class='item-action'>
                                          <a onclick=\"agregarProductoCart(".$producto['idSaldoInventario'].",1,'".$this->BasePath()."')\" class='item-add-btn'>
                                            <span class='icon-cart-text'>Add to Cart</span>
                                         </a>
                                       </div>
                                    </div>
                                 </div>";
                        }
                    ?>
                  </div>
                  <div class="lg-margin"></div>
               </div>
               <?php           
                    }
               ?>
            </div>
         </div>

      </div>
   </div>
</div>

<script>
    $(document).ready(function() {
            // Slider Revolution
            jQuery('#slider-rev').revolution({
                delay:8000,
                startwidth:$('.container').width(),
                startheight:400,
                onHoverStop:"true",
                hideThumbs:250,
                navigationHAlign:"center",
                navigationVAlign:"bottom",
                navigationHOffset:0,
                navigationVOffset:20,
                soloArrowLeftHalign:"left",
                soloArrowLeftValign:"center",
                soloArrowLeftHOffset:0,
                soloArrowLeftVOffset:0,
                soloArrowRightHalign:"right",
                soloArrowRightValign:"center",
                soloArrowRightHOffset:0,
                soloArrowRightVOffset:0,
                touchenabled:"on",
                stopAtSlide:-1,
                stopAfterLoops:-1,
                dottedOverlay:"none",
                fullWidth:"on",
                spinned:"spinner5",
                shadow:0,
                hideTimerBar: "on",
                // navigationStyle:"preview4"
              });

        });
</script>