<script type="text/javascript">
    $(document).ready(function() {
        $('#dtbuscarProveedorOficina').DataTable();   
        LimpiarModal('<?php echo $this->botonClose ?>','<?php echo $this->contenedorDialog ?>','<?php echo $this->modal ?>');
    });
</script>
<div class="row">
    <div class="col-lg-12">
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Proveedor Oficinas</strong> <small>Todas</small></h4></header>
                        <a class="btn btn-equal btn-sm btn-close" id="btnClosePop" style="float: right" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></a>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscarProveedorOficina" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Proveedor</th>
                                            <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Municipio</th>
                                            <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Web Site</th>
                                            <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">Email</th>
                                            <th lass="sorting" role="columnheader" tabindex="5" aria-controls="dtcrudindex" rowspan="1" colspan="1">Dirección</th>
                                            <th lass="sorting" role="columnheader" tabindex="6" aria-controls="dtcrudindex" rowspan="1" colspan="1">Telefono</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->registros as $obj) {
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$('#idProveedorOficina').val(".$obj['idProveedorOficina'].");$('#". $this->botonClose ."').click();\">
                                                    <td>".$obj['descripcionTercero']."</td>
                                                    <td>".$obj['descripcionMunicipio']."</td>
                                                    <td>".$obj['webSite']."</td>
                                                    <td>".$obj['email']."</td>
                                                    <td>".$obj['direccion']."</td>
                                                    <td>".$obj['telefono']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 