<?php
$form=$this->form;
$form->prepare();
//<====Si se envía un mensaje este se muestra=====> 
if ($this->msg != null) 
{
    echo "<script type='text/javascript'>".$this->msg."</script>";    
}
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-head">
                <header><h4 class="text-light">Formulario <strong>Proveedor Oficina</strong></h4></header>
            </div>
            <div class="box-body">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formInput($form->get('idProveedorOficina'));?>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Proveedor </label>
                        </div>
                        <div class="col-lg-4 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('idProveedor'));?>                            
                        </div>
                        <div class="col-lg-1">
                             <?php echo $this->formElement($form->get('btnBuscarProveedor'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Municipio </label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('idMunicipio'));?>                            
                        </div>
                        <div class="col-lg-1">
                             <?php echo $this->formElement($form->get('btnBuscarMunicipio'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Email</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('email'));?>                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Dirección</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                            <?php echo $this->formInput($form->get('direccion'));?>                            
                        </div>
                    </div>
                     <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-sm-3">
                            <label for="email1" class="control-label">Telefono</label>
                        </div>
                        <div class="col-lg-3 col-md-11 col-sm-9">
                             <?php echo $this->formElement($form->get('telefono'));?>                            
                        </div>
                    </div>
                    <div class="form-footer col-lg-offset-1 col-md-offset-2 col-sm-offset-3">
                        <?php   
                            echo $this->formElement($form->get('btnGuardar'));
                            echo $this->formElement($form->get('btnModificar'));
                            echo $this->formElement($form->get('btnEliminar'));
                            echo $this->formElement($form->get('btnCancelar'));
                        ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div><!--end .box -->
        <?php if (count($this->registros)>0) { ?>       
        <div class="row">  
            <div class="col-lg-12">
                <div class="box box-bordered">
                    <div class="box-head">
                        <header><h4 class="text-light"><strong>Oficinas Proveedor</strong> <small>Todas</small></h4></header>
                    </div>
                    <div class="box"> 
                        <div class="box-body table-responsive">
                            <div id="dtcrudindex_wrapper" class="dataTables_wrapper" role="grid">
                                <table id="dtbuscar" class="table table-striped table-hover dataTable" aria-describedby="dtcrudindex_info">
                                    <thead>
                                        <tr role="row">
                                            <th lass="sorting" role="columnheader" tabindex="0" aria-controls="dtcrudindex" rowspan="1" colspan="1">Proveedor</th>
                                            <th lass="sorting" role="columnheader" tabindex="1" aria-controls="dtcrudindex" rowspan="1" colspan="1">Municipio</th>
                                            <th lass="sorting" role="columnheader" tabindex="2" aria-controls="dtcrudindex" rowspan="1" colspan="1">Email</th>
                                            <th lass="sorting" role="columnheader" tabindex="3" aria-controls="dtcrudindex" rowspan="1" colspan="1">Dirección</th>
                                            <th lass="sorting" role="columnheader" tabindex="4" aria-controls="dtcrudindex" rowspan="1" colspan="1">Telefono</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         <?php 
                                        foreach ($this->registros as $obj) {
                                            echo "
                                                <tr class='gradeX odd' style='cursor:pointer' onClick=\"$(location).attr('href', '".$this->basePath()."/admin/proveedoroficina/index?id=".$obj['idProveedorOficina']."')\">
                                                    <td>".$obj['descripcionTercero']."</td>
                                                    <td>".$obj['descripcionMunicipio']."</td>
                                                    <td>".$obj['email']."</td>
                                                    <td>".$obj['direccion']."</td>
                                                    <td>".$obj['telefono']."</td>
                                                </tr>";
                                        }
                                        ?>
                                    </tbody>
                                </table>
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
 